# News To Stock Analyser 데이터준비

뉴스기사를 전달하면, 긍/부정분석 뿐아니라, 특정주식에 대한 긍/부정평가 처리 RAG 구현

In [2]:
from dotenv import load_dotenv
import os

load_dotenv()
os.environ['LANGSMITH_TRACING'] = 'true'
os.environ['LANGSMITH_ENDPOINT'] = 'https://api.smith.langchain.com'
os.environ['LANGSMITH_API_KEY'] = os.getenv('langsmith_key')
os.environ['LANGSMITH_PROJECT'] = 'skn23-langchain'
os.environ['OPENAI_API_KEY'] = os.getenv("openai_key")
os.environ['TAVILY_API_KEY'] = os.getenv("tavily_key")
os.environ['HF_TOKEN'] = os.getenv("HF_TOKEN") 
KAKAO_API_KEY = os.getenv("kakao_key")

## 데이터준비
https://huggingface.co/datasets/daekeun-ml/naver-news-summarization-ko

In [3]:
from datasets import load_dataset

dataset = load_dataset("daekeun-ml/naver-news-summarization-ko")

c:\Users\Playdata\llm\llm_venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [4]:
dataset

DatasetDict({
    train: Dataset({
        features: ['date', 'category', 'press', 'title', 'document', 'link', 'summary'],
        num_rows: 22194
    })
    validation: Dataset({
        features: ['date', 'category', 'press', 'title', 'document', 'link', 'summary'],
        num_rows: 2466
    })
    test: Dataset({
        features: ['date', 'category', 'press', 'title', 'document', 'link', 'summary'],
        num_rows: 2740
    })
})

In [5]:
economy_dataset = dataset["train"].filter(lambda row : row["category"] == "economy")
print(len(economy_dataset))

Filter: 100%|██████████| 22194/22194 [00:00<00:00, 67260.39 examples/s]

17088

In [6]:
import pandas as pd

df = economy_dataset.to_pandas()
df.head()

,date,category,press,title,document,link,summary
0,2022-07-03 17:14:37,economy,YTN,추경호 중기 수출지원 총력 무역금융 40조 확대,앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 ...,https://n.news.naver.com/mnews/article/052/000...,"올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록한 가운데, ..."
1,2022-07-04 08:07:12,economy,아시아경제,해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다,문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준...,https://n.news.naver.com/mnews/article/277/000...,인터엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타...
2,2022-07-01 08:51:12,economy,뉴시스,에디슨이노 이승훈 제이스페이스 대표 사내이사 선임,기사내용 요약 우주발사체 사업 본격화 서울 뉴시스 김경택 기자 에디슨이노가 우주발사...,https://n.news.naver.com/mnews/article/003/001...,에디슨이노는 1일 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이...
3,2022-07-01 16:11:01,economy,머니투데이,SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차,SK바이오사이언스가 글로벌 사업의 고도화를 위해 조직 개편을 단행했다. SK바이오사...,https://n.news.naver.com/mnews/article/008/000...,SK바이오사이언스가 글로벌 사업의 고도화를 위해 기존 해외사업개발실을 백신사업뿐만 ...
4,2022-07-01 21:48:04,economy,경향신문,금융당국 “증시 변동성 완화 조치”,4일부터 석달간 증권사 신용융자담보비율 유지의무 면제 금융당국이 코스피지수가 장중 ...,https://n.news.naver.com/mnews/article/032/000...,1일 1일 금융위원회는 증권 유관기관과 금융시장합동점검회의를 열고 코스피지수가 장중...

## sLLM 답변데이터 생성
llm을 이용해서 sLLM이 답변했으면 하는 내용을 생성해낸다. 이때 답변을 품질이 중요하므로, 되도록 상위모델을 사용하는 것이 좋다.

In [7]:
from pydantic import BaseModel, Field
from typing import List, Optional
from langchain_core.prompts import ChatPromptTemplate

class StockAnalysis(BaseModel):
    stock_related: bool = Field(description = "뉴스와 주식 종목간의 연관성 여부")
    summary: str = Field(description = "뉴스 요약")

    positive_stocks: List[str] = Field(description = "긍정적 영향이 예상되는 주식 종목명 목록", default_factory = list)
    positive_keywords: List[str] = Field(description = "긍정적 영향의 근거가 되는 키워드 목록", default_factory = list)
    positive_reasons: List[str] = Field(description = "긍정적 영향이 예상되는 이유", default_factory = list)
    
    negative_stocks: List[str] = Field(description = "부정적 영향이 예상되는 주식 종목명 목록", default_factory = list)
    negative_keywords: List[str] = Field(description = "부정적 영향의 근거가 되는 키워드 목록", default_factory = list)
    negative_reasons: List[str] = Field(description = "부정적 영향이 예상되는 이유", default_factory = list)

In [8]:
system_prompt = '''  # 모델 역할/출력 규칙을 고정하는 시스템 프롬프트
당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,
특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.

다음 출력지시사항을 지켜주세요.
1. 뉴스와 종목간의 연관성을 발견할 수 없다면:
    - stock_related를 False로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
2. 뉴스와 종목간의 연관성을 발견했다면:
    - stock_related를 True로 작성하세요.
    - summary에 뉴스의 요약을 작성하세요.
    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.
    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.
    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.
'''

user_prompt = '''  # 분석 대상 뉴스 본문을 전달하는 사용자 프롬프트
다음 뉴스기사의 내용에 대해 심층적인 분석을 수행해주세요.

[news]
{news}
'''

prompt = ChatPromptTemplate.from_messages([
    ('system', system_prompt),
    ('human', user_prompt)
])

news = df['document'][1]
prompt.invoke({'news': news})

ChatPromptValue(messages=[SystemMessage(content="  # 모델 역할/출력 규칙을 고정하는 시스템 프롬프트\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n    - stock_related를 False로 작성하세요.\n    - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n    - stock_related를 True로 작성하세요.\n    - summary에 뉴스의 요약을 작성하세요.\n    - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n    - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n    - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n", additional_kwargs={}, response_metadata={}), HumanMessage(content='  # 분석 대상 뉴스 본문을 전달하는 사용자 프롬프트\n다음 뉴스기사의 내용에 대해 심층적인 분석을 수행해주세요.\n\n[news]\n문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준비 7 8월 2만5000원 추가 시 와인 5종 및 생맥주 무제한 제공 인터컨티넨탈 서울 코엑스 브래서리 쿨 섬머 페스타 . 인터컨티넨탈 서울 코엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타 를 진행한다고 4일 밝혔다. 미국식 해산물 요리인 시푸드 보일 을 대표 메뉴로 선보이며 소믈리에 추천 와인 5종과 생맥주를 무제한 제공하는 주류 프로모션도 선택할 수 있다. 시푸드 보일 이 대표 메뉴로 준비되고 라이브 스테이션에서 셰프가 직접 원하는 메뉴를 먹기 좋게 잘라 제공한다. 시푸드 보일은 문어와 랍스터 대게 갑오징어 새우 소라 관자 낙지 등 해산물을 쪄낸 뒤 셰프의 비법 시즈닝으로 이국적인 감칠맛을 더한 메뉴다. 프로모션 기간에는 해물전 가리비 불도장 장어 데마끼 로제 해물 뇨끼 등 한식 중식 일식 양식 등 세계 각국의 해산물 메뉴도 즐길 수 있다. 소믈리에 추천 와인 5종과 생맥주를 무제한으로 제공하는 옵션도 선택할 수 있다. 제공되는 와인은 레드와 화이트 와인 각 2종 스파클링 와인 1종으로 취향에 따라 다양하게 즐길 수 있다. 해당 기간 동안 입구 와인셀렉션 코너에서 10만원 이상 와인 구매 시 호텔에서 제작한 주트백도 선물로 증정한다. 이용 가격은 이전과 동일하며 네이버 예약 시 10% 할인 혜택도 제공한다. 주류 무제한 혜택은 2만5000원 추가 시 이용할 수 있다.\n', additional_kwargs={}, response_metadata={})])

In [9]:
from langchain.chat_models import init_chat_model

llm = init_chat_model("openai:gpt-4.1-mini")
chain = prompt | llm.with_structured_output(StockAnalysis) 

def analyze_news(news):
    return chain.invoke({"news" : news})

analyze_news(news)

StockAnalysis(stock_related=False, summary="인터컨티넨탈 서울 코엑스의 뷔페 레스토랑 브래서리가 6월 6일부터 8월 31일까지 '쿨 섬머 페스타'를 진행한다. 대표 메뉴인 미국식 해산물 찜인 시푸드 보일을 비롯해 다양한 해산물 요리를 제공하며, 소믈리에 추천 와인 5종과 생맥주 무제한 제공 옵션도 선택 가능하다. 프로모션 기간 와인 구매자에게는 주트백 증정, 네이버 예약 시 할인 혜택도 제공된다.", positive_stocks=[], positive_keywords=[], positive_reasons=[], negative_stocks=[], negative_keywords=[], negative_reasons=[])

In [10]:
news = df["document"][100]
print(news)
print()

analyze_news(news)

해수부 5일 개정 공유수면 관리 및 매립에 관한 법률 시행 헤럴드경제 홍태화 기자 앞으로 공유수면관리청이 어업·환경 등에 영향을 미칠 것으로 예상되는 공유수면 점용·사용 허가를 할 때 미리 어업인 등 이해관계자들의 의견을 들어야 한다. 해양수산부는 5일 이같은 내용이 담긴 개정 공유수면 관리 및 매립에 관한 법률과 같은 법 시행령·시행규칙이 이날부터 시행된다고 밝혔다. 바다·바닷가·하천 등 공유수면은 공유재이기 때문에 이를 점용·사용하기 위해서는 별도의 허가를 받아야 한다. 최근 해상풍력 발전시설 해변을 이용한 관광시설 등 대규모 시설이 공유수면을 장기적으로 점용·사용하는 경우가 늘어났지만 이해 관계자의 의견을 사전에 수렴할 수 없는 문제가 있었다. 이에 공유수면 점용·사용으로 인한 사회적 갈등이 증가했다. 이러한 문제를 해결하기 위해 해수부는 지난 1월 공유수면 점용·사용 허가를 할 때 이해관계자의 의견을 듣도록 공유수면 관리 및 매립에 관한 법률을 개정했다. 법 개정에 따라 공유수면관리청이 해양환경·수산자원·자연경관 보호 등에 영향을 끼칠 수 있는 공유수면 점용·사용 신청을 받은 경우 이를 관보 공보 와 인터넷 홈페이지에 공고해야 한다. 또 점용·사용 허가를 했을 때 피해를 볼 것으로 예상되는 어업인에 대한 의견 조사도 별도로 진행해야 한다. 황준성 해수부 해양공간정책과장은 공유수면 점용·사용으로 인한 이해 관계자의 피해를 방지하려는 법령 개정의 취지를 달성할 수 있도록 각 공유수면관리청과 협력해 관련 제도의 차질 없는 운영을 지원하겠다 고 말했다.

StockAnalysis(stock_related=False, summary='해양수산부가 공유수면 관리 및 매립에 관한 법률을 개정하여, 공유수면 점용 및 사용 허가 시 어업인 등 이해관계자의 의견을 사전에 수렴하도록 하는 내용을 포함해 5일부터 시행한다. 이번 법 개정은 공유수면 점용·사용으로 인한 사회적 갈등을 완화하고 해양환경 및 수산자원 보호를 강화하기 위한 조치다. 해수부는 관련 제도의 원활한 운영을 위해 공유수면관리청과 협력할 계획이다.', positive_stocks=[], positive_keywords=[], positive_reasons=[], negative_stocks=[], negative_keywords=[], negative_reasons=[])

In [11]:
df = df[:50]
df["content"] = df["title"] + "\n" + df["document"]

pd.set_option("display.max_colwidth", None)
df["content"].head()

0                                                                                                                                                                      추경호 중기 수출지원 총력 무역금융 40조 확대\n앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 했습니다. 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했습니다. 류환홍 기자가 보도합니다. 기자 수출은 최고의 실적을 보였지만 수입액이 급증하면서 올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록했습니다. 정부가 수출확대에 총력을 기울이기로 한 것은 원자재 가격 상승 등 대외 리스크가 가중되는 상황에서 수출 증가세 지속이야말로 한국경제의 회복을 위한 열쇠라고 본 것입니다. 추경호 경제부총리 겸 기획재정부 장관 정부는 우리 경제의 성장엔진인 수출이 높은 증가세를 지속할 수 있도록 총력을 다하겠습니다. 우선 물류 부담 증가 원자재 가격 상승 등 가중되고 있는 대외 리스크에 대해 적극 대응하겠습니다. 특히 중소기업과 중견기업 수출 지원을 위해 무역금융 규모를 연초 목표보다 40조 원 늘린 301조 원까지 확대하고 물류비 부담을 줄이기 위한 대책도 마련했습니다. 이창양 산업통상자원부 장관 국제 해상운임이 안정될 때까지 월 4척 이상의 임시선박을 지속 투입하는 한편 중소기업 전용 선복 적재 용량 도 현재보다 주당 50TEU 늘려 공급하겠습니다. 하반기에 우리 기업들의 수출 기회를 늘리기 위해 2 500여 개 수출기업을 대상으로 해외 전시회 참가를 지원하는 등 마케팅 지원도 벌이기로 했습니다. 정부는 또 이달 중으로 반도체를 비롯한 첨단 산업 육성 전략을 마련해 수출 증가세를 뒷받침하고 에너지 소비를 줄이기 위한 효율화 방안을 마련해 무역수지 개선에 나서기로 했습니다. YTN 류환홍입니다.
1                                                                                                                                                                                                                                                                     해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다\n문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준비 7 8월 2만5000원 추가 시 와인 5종 및 생맥주 무제한 제공 인터컨티넨탈 서울 코엑스 브래서리 쿨 섬머 페스타 . 인터컨티넨탈 서울 코엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타 를 진행한다고 4일 밝혔다. 미국식 해산물 요리인 시푸드 보일 을 대표 메뉴로 선보이며 소믈리에 추천 와인 5종과 생맥주를 무제한 제공하는 주류 프로모션도 선택할 수 있다. 시푸드 보일 이 대표 메뉴로 준비되고 라이브 스테이션에서 셰프가 직접 원하는 메뉴를 먹기 좋게 잘라 제공한다. 시푸드 보일은 문어와 랍스터 대게 갑오징어 새우 소라 관자 낙지 등 해산물을 쪄낸 뒤 셰프의 비법 시즈닝으로 이국적인 감칠맛을 더한 메뉴다. 프로모션 기간에는 해물전 가리비 불도장 장어 데마끼 로제 해물 뇨끼 등 한식 중식 일식 양식 등 세계 각국의 해산물 메뉴도 즐길 수 있다. 소믈리에 추천 와인 5종과 생맥주를 무제한으로 제공하는 옵션도 선택할 수 있다. 제공되는 와인은 레드와 화이트 와인 각 2종 스파클링 와인 1종으로 취향에 따라 다양하게 즐길 수 있다. 해당 기간 동안 입구 와인셀렉션 코너에서 10만원 이상 와인 구매 시 호텔에서 제작한 주트백도 선물로 증정한다. 이용 가격은 이전과 동일하며 네이버 예약 시 10% 할인 혜택도 제공한다. 주류 무제한 혜택은 2만5000원 추가 시 이용할 수 있다.
2                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   에디슨이노 이승훈 제이스페이스 대표 사내이사 선임\n기사내용 요약 우주발사체 사업 본격화 서울 뉴시스 김경택 기자 에디슨이노가 우주발사체 사업에 본격 진출한다고 1일 밝혔다. 에디슨이노는 전날 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이스홀딩스 대표이사를 사내이사로 선임했다. 이날 사업 목적에 위성체 발사와 우주선 위성시스템 등 항공 우주 분야와 자율 주행·그래핀 관련 사업을 사업목적에 추가했다. 사내이사에 이승영 카이스트 정밀기계공학 박사를 영입해 임플란트 관련 연구·생산기술을 보강했다. 서울대 화학생물공학 출신 최도영 씨도 선임해 현재 임상 시험계획 승인을 받은 생체흡수성 금속 리조멧 사업 확대를 도모한다 계획이다. 골절 수술 시 인체에 흡수되는 소재인 리조멧은 국내 임상 계획 승인과 중국 내 임상승인에 요구되는 시험을 통과한 상태다.
3    SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차\nSK바이오사이언스가 글로벌 사업의 고도화를 위해 조직 개편을 단행했다. SK바이오사이언스는 기존 해외사업개발실을 BD Business Development 1 3실로 확대 재편하고 글로벌 규제 및 허가 전담 조직인 Global RA Regulatory Affairs 실을 신설한다고 1일 밝혔다. SK바이오사이언스는 지난해 코로나19 COVID 19 백신 위탁 생산 등으로 주목받는 백신 기업으로 부상하며 글로벌 사업의 영역과 규모가 급속도로 성장 중이다. 이러한 성장 속도에 맞춰 기존 전담 조직인 해외사업개발실을 보다 세분화 및 전문화하고자 BD 1 3실로 확대 재편했다. BD 1 3실은 앞으로 기존에 영위 중인 백신 사업뿐만 아니라 세포·유전자치료제 CGT 등 신규 사업에 대한 △글로벌 네트워크들과의 공동 개발 △신규 C D MO 수주 △개발 제품 상업화 등 다양한 영역의 사업을 고도화하고 실행력을 높이는 업무를 담당한다. 또한 Global RA실을 신설해 미국 유럽 등 해외 선진국의 GMP Good Manufacturing Practice 를 확보하는 등 국제적인 수준의 관련 인증 및 허가 획득에도 더욱 박차를 가할 방침이다. CMC팀도 신설됐다. CMC는 화학 Chemistry 제조 Manufacturing 품질 Control 의 약자다. CMC팀은 완제 의약품을 만드는 공정 개발 process development 과 품질 관리 quality control 부문에서 핵심적인 역할을 수행한다. 연구부터 임상 허가 생산 품질에 이르는 GMP 관련 제반 업무를 관리한다. SK바이오사이언스는 이번 조직 개편이 글로벌 탑티어 바이오 기업으로의 성장을 더욱 앞당기고 초격차 경쟁력 확보의 계기가 될 것으로 기대하고 있다. SK바이오사이언스는 지난달 29일 국내 최초 코로나19 백신인 스카이코비원 SKYCovione 멀티주 의 품목허가를 획득했다. 이어 국가출하승인 및 WHO 등 해외 승인을 통해 국내외 백신 시장에 본격 진출할 예정이다.
4                                                                                                                                                                                                                                                  금융당국 “증시 변동성 완화 조치”\n4일부터 석달간 증권사 신용융자담보비율 유지의무 면제 금융당국이 코스피지수가 장중 2300 아래까지 떨어지자 주식시장 변동성을 완화하는 조치를 시행하기로 했다. 금융위원회는 1일 주식시장 마감 후 김소영 부위원장 주재로 증권 유관기관과 금융시장합동점검회의를 열고 변동성 완화조치를 시행하기로 했다고 밝혔다. 이에 따라 다음 주식시장 개장일인 오는 4일부터 9월30일까지 3개월간 증권사의 신용융자담보비율 유지의무가 면제된다. 신용융자담보비율 유지의무란 증권사가 일명 ‘빚투’ 빚내서 투자 자금인 신용융자를 시행할 때 담보를 140% 이상 확보하고 내규에서 정한 담보비율을 유지할 것을 요구하는 규제다. 유지의무 면제는 증권사의 신용융자 담보주식에 대한 과도한 반대매매를 억제하기 위한 조치다. 금융당국은 코로나19 사태가 본격화한 2020년 3월에도 이 같은 조치를 6개월간 시행한 바 있다. 7일부터 10월6일까지는 상장기업의 하루 자기주식 매수 주문 수량 한도 제한도 완화된다. 신탁취득 주식도 발행주식총수의 1% 이내에서 신탁재산 총액 범위 내로 한시적으로 확대된다. 이와 함께 금융위는 금융감독원과 한국거래소 합동으로 공매도 특별점검을 실시해 공매도 현황과 시장교란 가능성 등을 살펴보기로 했다. 현재 공매도는 지난해 5월 이후 제한적으로 실시되고 있다. 금융위와 금감원은 매주 금요일 금융시장합동점검회의를 열어 증시 등 금융시장상황을 점검할 예정이다. 금융당국은 “컨틴전시플랜에 따라 필요한 시장 변동성 완화 조치를 검토·시행해 나갈 것”이라고 말했다.
Name: content, dtype: object

In [13]:
# LLM 질의 & 데이터 생성
from tqdm.auto import tqdm  # 프로그레스바

results = []    # 분석 결과 저장 리스트

for content in tqdm(df['content']):
    result = analyze_news(content)  # 분석 진행([StockAnalysis]형태로 반환)
    results.append(result)          # 리스트에 추가
    
df['result'] = results              # 결과 리스트를 DF result 컬럼으로 추가
df.head()

100%|██████████| 50/50 [02:14<00:00,  2.68s/it]

,date,category,press,title,document,link,summary,content,result
0,2022-07-03 17:14:37,economy,YTN,추경호 중기 수출지원 총력 무역금융 40조 확대,앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 했습니다. 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했습니다. 류환홍 기자가 보도합니다. 기자 수출은 최고의 실적을 보였지만 수입액이 급증하면서 올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록했습니다. 정부가 수출확대에 총력을 기울이기로 한 것은 원자재 가격 상승 등 대외 리스크가 가중되는 상황에서 수출 증가세 지속이야말로 한국경제의 회복을 위한 열쇠라고 본 것입니다. 추경호 경제부총리 겸 기획재정부 장관 정부는 우리 경제의 성장엔진인 수출이 높은 증가세를 지속할 수 있도록 총력을 다하겠습니다. 우선 물류 부담 증가 원자재 가격 상승 등 가중되고 있는 대외 리스크에 대해 적극 대응하겠습니다. 특히 중소기업과 중견기업 수출 지원을 위해 무역금융 규모를 연초 목표보다 40조 원 늘린 301조 원까지 확대하고 물류비 부담을 줄이기 위한 대책도 마련했습니다. 이창양 산업통상자원부 장관 국제 해상운임이 안정될 때까지 월 4척 이상의 임시선박을 지속 투입하는 한편 중소기업 전용 선복 적재 용량 도 현재보다 주당 50TEU 늘려 공급하겠습니다. 하반기에 우리 기업들의 수출 기회를 늘리기 위해 2 500여 개 수출기업을 대상으로 해외 전시회 참가를 지원하는 등 마케팅 지원도 벌이기로 했습니다. 정부는 또 이달 중으로 반도체를 비롯한 첨단 산업 육성 전략을 마련해 수출 증가세를 뒷받침하고 에너지 소비를 줄이기 위한 효율화 방안을 마련해 무역수지 개선에 나서기로 했습니다. YTN 류환홍입니다.,https://n.news.naver.com/mnews/article/052/0001759333?sid=101,"올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록한 가운데, 정부가 하반기에 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 결정한 가운데, 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했다.",추경호 중기 수출지원 총력 무역금융 40조 확대\n앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 했습니다. 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했습니다. 류환홍 기자가 보도합니다. 기자 수출은 최고의 실적을 보였지만 수입액이 급증하면서 올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록했습니다. 정부가 수출확대에 총력을 기울이기로 한 것은 원자재 가격 상승 등 대외 리스크가 가중되는 상황에서 수출 증가세 지속이야말로 한국경제의 회복을 위한 열쇠라고 본 것입니다. 추경호 경제부총리 겸 기획재정부 장관 정부는 우리 경제의 성장엔진인 수출이 높은 증가세를 지속할 수 있도록 총력을 다하겠습니다. 우선 물류 부담 증가 원자재 가격 상승 등 가중되고 있는 대외 리스크에 대해 적극 대응하겠습니다. 특히 중소기업과 중견기업 수출 지원을 위해 무역금융 규모를 연초 목표보다 40조 원 늘린 301조 원까지 확대하고 물류비 부담을 줄이기 위한 대책도 마련했습니다. 이창양 산업통상자원부 장관 국제 해상운임이 안정될 때까지 월 4척 이상의 임시선박을 지속 투입하는 한편 중소기업 전용 선복 적재 용량 도 현재보다 주당 50TEU 늘려 공급하겠습니다. 하반기에 우리 기업들의 수출 기회를 늘리기 위해 2 500여 개 수출기업을 대상으로 해외 전시회 참가를 지원하는 등 마케팅 지원도 벌이기로 했습니다. 정부는 또 이달 중으로 반도체를 비롯한 첨단 산업 육성 전략을 마련해 수출 증가세를 뒷받침하고 에너지 소비를 줄이기 위한 효율화 방안을 마련해 무역수지 개선에 나서기로 했습니다. YTN 류환홍입니다.,"stock_related=True summary='정부가 수출 확대를 위해 무역금융 규모를 40조 원 이상 확대하고, 물류비 지원과 임시선박 투입 등 수출 중소기업 지원 대책을 추진키로 했습니다. 또한 반도체 등 첨단 산업 육성 전략과 에너지 효율화 방안도 마련해 무역수지 개선에 나설 계획입니다.' positive_stocks=['삼성전자', 'SK하이닉스', '현대글로비스', '팬오션'] positive_keywords=['무역금융 확대', '물류비 지원', '임시선박 투입', '첨단산업 육성', '수출 확대'] positive_reasons=['무역금융 확대와 물류비 절감 대책은 수출 중소기업의 경쟁력 강화에 긍정적 영향', '임시선박 투입으로 물류난 해소 기대', '반도체 등 첨단 산업 육성 전략은 수출 주도 산업 강화와 관련주에 긍정적', '현대글로비스, 팬오션 등 물류 관련 기업은 물류 지원 정책 수혜 예상'] negative_stocks=[] negative_keywords=[] negative_reasons=[]"
1,2022-07-04 08:07:12,economy,아시아경제,해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다,문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준비 7 8월 2만5000원 추가 시 와인 5종 및 생맥주 무제한 제공 인터컨티넨탈 서울 코엑스 브래서리 쿨 섬머 페스타 . 인터컨티넨탈 서울 코엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타 를 진행한다고 4일 밝혔다. 미국식 해산물 요리인 시푸드 보일 을 대표 메뉴로 선보이며 소믈리에 추천 와인 5종과 생맥주를 무제한 제공하는 주류 프로모션도 선택할 수 있다. 시푸드 보일 이 대표 메뉴로 준비되고 라이브 스테이션에서 셰프가 직접 원하는 메뉴를 먹기 좋게 잘라 제공한다. 시푸드 보일은 문어와 랍스터 대게 갑오징어 새우 소라 관자 낙지 등 해산물을 쪄낸 뒤 셰프의 비법 시즈닝으로 이국적인 감칠맛을 더한 메뉴다. 프로모션 기간에는 해물전 가리비 불도장 장어 데마끼 로제 해물 뇨끼 등 한식 중식 일식 양식 등 세계 각국의 해산물 메뉴도 즐길 수 있다. 소믈리에 추천 와인 5종과 생맥주를 무제한으로 제공하는 옵션도 선택할 수 있다. 제공되는 와인은 레드와 화이트 와인 각 2종 스파클링 와인 1종으로 취향에 따라 다양하게 즐길 수 있다. 해당 기간 동안 입구 와인셀렉션 코너에서 10만원 이상 와인 구매 시 호텔에서 제작한 주트백도 선물로 증정한다. 이용 가격은 이전과 동일하며 네이버 예약 시 10% 할인 혜택도 제공한다. 주류 무제한 혜택은 2만5000원 추가 시 이용할 수 있다.,https://n.news.naver.com/mnews/article/277/0005112302?sid=101,인터엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타 를 진행하는데 미국식 해산물 요리인 시푸드 보일 을 대표 메뉴로 선보이며 소믈리에 추천 와인 5종과 생맥주를 무제한 제공하는 주류 프로모션도 선택할 수 있으며 프로모션 기간에는 해물전 가리비 불도장 장어 데마끼 로제 해물 뇨끼 등 한식 중식 일식 양식 등 세계 각국의 해산물 메뉴도 즐길 수 있다.,해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다\n문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준비 7 8월 2만5000원 추가 시 와인 5종 및 생맥주 무제한 제공 인터컨티넨탈 서울 코엑스 브래서리 쿨 섬머 페스타 . 인터컨티넨탈 서울 코엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타 를 진행한다고 4일 밝혔다. 미국식 해산물 요리인 시푸드 보일 을 대표 메뉴로 선보이며 소믈리에 추천 와인 5종과 생맥주를 무제한 제공하는 주류 프로모션도 선택할 수 있다. 시푸드 보일 이 대표 메뉴로 준비되고 라이브 스테이션에서 셰프가 직접 원하는 메뉴를 먹기 좋게 잘라 제공한다. 시푸드 보일은 문어와 랍스터 대게 갑오징어 새우 소라 관자 낙지 등 해산물을 쪄낸 뒤 셰프의 비법 시즈닝으로 이국적인 감칠맛을 더한 메뉴다. 프로모션 기간에는 해물전 가리비 불도장 장어 데마끼 로제 해물 뇨끼 등 한식 중식 일식 양식 등 세계 각국의 해산물 메뉴도 즐길 수 있다. 소믈리에 추천 와인 5종과 생맥주를 무제한으로 제공하는 옵션도 선택할 수 있다. 제공되는 와인은 레드와 화이트 와인 각 2종 스파클링 와인 1종으로 취향에 따라 다양하게 즐길 수 있다. 해당 기간 동안 입구 와인셀렉션 코너에서 10만원 이상 와인 구매 시 호텔에서 제작한 주트백도 선물로 증정한다. 이용 가격은 이전과 동일하며 네이버 예약 시 10% 할인 혜택도 제공한다. 주류 무제한 혜택은 2만5000원 추가 시 이용할 수 있다.,"stock_related=False summary=""인터컨티넨탈 서울 코엑스 뷔페 레스토랑이 여름 한정으로 '쿨 섬머 페스타'를 진행한다. 주요 메뉴로 시푸드 보일(미국식 해산물 찜)을 선보이고, 문어, 랍스터, 대게 등 다양한 해산물을 활용한다. 7~8월 동안 2만5000원 추가 시 와인 5종과 생맥주를 무제한으로 제공하는 주류 프로모션을 선택할 수 있다. 다양한 해산물 요리와 세계 각국의 메뉴도 즐길 수 있으며, 네이버 예약 할인 혜택과 와인 구매 시 주트백 증정 이벤트도 있다."" positive_stocks=[] positive_keywords=[] positive_reasons=[] negative_stocks=[] negative_keywords=[] negative_reasons=[]"
2,2022-07-01 08:51:12,economy,뉴시스,에디슨이노 이승훈 제이스페이스 대표 사내이사 선임,기사내용 요약 우주발사체 사업 본격화 서울 뉴시스 김경택 기자 에디슨이노가 우주발사체 사업에 본격 진출한다고 1일 밝혔다. 에디슨이노는 전날 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이스홀딩스 대표이사를 사내이사로 선임했다. 이날 사업 목적에 위성체 발사와 우주선 위성시스템 등 항공 우주 분야와 자율 주행·그래핀 관련 사업을 사업목적에 추가했다. 사내이사에 이승영 카이스트 정밀기계공학 박사를 영입해 임플란트 관련 연구·생산기술을 보강했다. 서울대 화학생물공학 출신 최도영 씨도 선임해 현재 임상 시험계획 승인을 받은 생체흡수성 금속 리조멧 사업 확대를 도모한다 계획이다. 골절 수술 시 인체에 흡수되는 소재인 리조멧은 국내 임상 계획 승인과 중국 내 임상승인에 요구되는 시험을 통과한 상태다.,https://n.news.naver.com/mnews/article/003/0011279060?sid=101,에디슨이노는 1일 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이스홀딩스 대표이사를 사내이사로 선임하고 위성체 발사와 우주선 위성시스템 등 항공 우주 분야와 자율 주행·그래핀 관련 사업을 사업목적에 추가하여 우주발사체 사업에 본격 진출한다고 1일 밝혔다.,에디슨이노 이승훈 제이스페이스 대표 사내이사 선임\n기사내용 요약 우주발사체 사업 본격화 서울 뉴시스 김경택 기자 에디슨이노가 우주발사체 사업에 본격 진출한다고 1일 밝혔다. 에디슨이노는 전날 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이스홀딩스 대표이사를 사내이사로 선임했다. 이날 사업 목적에 위성체 발사와 우주선 위성시스템 등 항공 우주 분야와 자율 주행·그래핀 관련 사업을 사업목적에 추가했다. 사내이사에 이승영 카이스트 정밀기계공학 박사를 영입해 임플란트 관련 연구·생산기술을 보강했다. 서울대 화학생물공학 출신 최도영 씨도 선임해 현재 임상 시험계획 승인을 받은 생체흡수성 금속 리조멧 사업 확대를 도모한다 계획이다. 골절 수술 시 인체에 흡수되는 소재인 리조멧은 국내 임상 계획 승인과 중국 내 임상승인에 요구되는 시험을 통과한 상태다.,"stock_related=True summary='에디슨이노는 이노시스로 사명을 변경하고 우주발사체 및 위성시스템 등 항공우주 사업에 본격 진출한다. 이승훈 제이스페이스홀딩스 대표를 사내이사로 선임하며 우주 분야 역량을 강화했다. 또한 임플란트 연구개발과 생체흡수성 금속 리조멧 사업도 확장할 계획이다.' positive_stocks=['에디슨이노'] positive_keywords=['우주발사체', '항공우주 사업 진출', '사내이사 선임', '위성시스템', '생체흡수성 금속 리조멧'] positive_reasons=['우주발사체와 위성시스템 등 신사업 진출로 성장 동력 확보', '제이스페이스홀딩스 대표 선임을 통한 전문성 강화', '임플란트 및 생체흡수성 금속 사업 확대가 추가 성장 기대요인'] negative_stocks=[] negative_keywords=[] negative_reasons=[]"
3,2022-07-01 16:11:01,economy,머니투데이,SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차,SK바이오사이언스가 글로벌 사업의 고도화를 위해 조직 개편을 단행했다. SK바이오사이언스는 기존 해외사업개발실을 BD Business Development 1 3실로 확대 재편하고 글로벌 규제 및 허가 전담 조직인 Global RA Regulatory Affairs 실을 신설한다고 1일 밝혔다. SK바이오사이언스는 지난해 코로나19 COVID 19 백신 위탁 생산 등으로 주목받는 백신 기업으로 부상하며 글로벌 사업의 영역과 규모가 급속도로 성장 중이다. 이러한 성장 속도에 맞춰 기존 전담 조직인 해외사업개발실을 보다 세분화 및 전문화하고자 BD 1 3실로 확대 재편했다. BD 1 3실은 앞으로 기존에 영위 중인 백신 사업뿐만 아니라 세포·유전자치료제 CGT 등 신규 사업에 대한 △글로벌 네트워크들과의 공동 개발 △신규 C D MO 수주 △개발 제품 상업화 등 다양한 영역의 사업을 고도화하고 실행력을 높이는 업무를 담당한다. 또한 Global RA실을 신설해 미국 유럽 등 해외 선진국의 GMP Good Manufacturing Practice 를 확보하는 등 국제적인 수준의 관련 인증 및 허가 획득에도 더욱 박차를 가할 방침이다. CMC팀도 신설됐다. CMC는 화학 Chemistry 제조 Manufacturing 품질 Control 의 약자다. CMC팀은 완제 의약품을 만드는 공정 개발 process development 과 품질 관리 quality control 부문에서 핵심적인 역할을 수행한다. 연구부터 임상 허가 생산 품질에 이르는 GMP 관련 제반 업무를 관리한다. SK바이오사이언스는 이번 조직 개편이 글로벌 탑티어 바이오 기업으로의 성장을 더욱 앞당기고 초격차 경쟁력 확보의 계기가 될 것으로 기대하고 있다. SK바이오사이언스는 지난달 29일 국내 최초 코로나19 백신인 스카이코비원 SKYCovione 멀티주 의 품목허가를 획득했다. 이어 국가출하승인 및 WHO 등 해외 승인을 통해 국내외 백신 시장에 본격 진출할 예정이다.,https://n.news.naver.com/mnews/article/008/0004765787?sid=101,SK바이오사이언스가 글로벌 사업의 고도화를 위해 기존 해외사업개발실을 백신사업뿐만 아니라 다양한 영역의 사업을 고도화하고 실행력을 높이는 업무를 담당하는 1 3실로 확대 재편하고 글로벌 규제 및 허가 전담 조직을 신설한다고 1일 밝혔다.,SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차\nSK바이오사이언스가 글로벌 사업의 고도화를 위해 조직 개편을 단행했다. SK바이오사이언스는 기존 해외사업개발실을 BD Business Development 1 3실로 확대 재편하고 글로벌 규제 및 허가 전담 조직인 Global RA Regulatory Affairs 실을 신설한다고 1일 밝혔다. SK바이오사이언스는 지난해 코로나19 COVID 19 백신 위탁 생산 등으로 주목받는 백신 기업으로 부상하며 글로벌 사업의 영역과 규모가 급속도로 성장 중이다. 이러한 성장 속도에 맞춰 기존 전담 조직인 해외사업개발실을 보다 세분화 및 전문화하고자 BD 1 3실로 확대 재편했다. BD 1 3실은 앞으로 기존에 영위 중인 백신 사업뿐만 아니라 세포·유전자치료제 CGT 등 신규 사업에 대한 △글로벌 네트워크들과의 공동 개발 △신규 C D MO 수주 △개발 제품 상업화 등 다양한 영역의 사업을 고도화하고 실행력을 높이는 업무를 담당한다. 또한 Global RA실을 신설해 미국 유럽 등 해외 선진국의 GMP Good Manufacturing Practice 를 확보하는 등 국제적인 수준의 관련 인증 및 허가 획득에도 더욱 박차를 가할 방침이다. CMC팀도 신설됐다. CMC는 화학 Chemistry 제조 Manufacturing 품질 Control 의 약자다. CMC팀은 완제 의약품을 만드는 공정 개발 process development 과 품질 관리 quality control 부문에서 핵심적인 역할을 수행한다. 연구부터 임상 허가 생산 품질에 이르는 GMP 관련 제반 업무를 관리한다. SK바이오사이언스는 이번 조직 개편이 글로벌 탑티어 바이오 기업으로의 성장을 더욱 앞당기고 초격차 경쟁력 확보의 계기가 될 것으로 기대하고 있다. SK바이오사이언스는 지난달 29일 국내 최초 코로나19 백신인 스카이코비원 SKYCovione 멀티주 의 품목허가를 획득했다. 이어 국가출하승인 및 WHO 등 해외 승인을 통해 국내외 백신 시장에 본격 진출할 예정이다.,"stock_related=True summary='SK바이오사이언스는 글로벌 사업의 고도화를 위해 해외사업 조직을 BD 1-3실로 세분화하고, 글로벌 규제 및 허가 전담 조직인 Global RA실과 의약품 공정개발 및 품질관리 담당 CMC팀을 신설했다. 코로나19 백신 위탁생산을 통해 급성장한 동사는 이번 조직개편으로 글로벌 백신 시장 진출과 세포·유전자치료제 등 신규 사업 고도화에 박차를 가하고 있으며, 국내 최초 코로나19 백신 품목허가를 획득해 시장 경쟁력을 강화하고 있다.' positive_stocks=['SK바이오사이언스'] positive_keywords=['글로벌 사업 고도화', '조직 개편', '백신 사업 확장', '신규 사업', '규제 및 허가 전담 조직', 'CMC팀 신설', '코로나19 백신 품목허가'] positive_reasons=['조직 개편으로 글로벌 네트워크와 공동 개발 및 신규 수주가 강화되어 사업 실행력이 높아짐', 'Global RA실 신설로 미국, 유럽 등 선진국 GMP 인증 및 허가 획득 탄력 전망', 'CMC팀 신설로 공정 개발과 품질 관리 강화되어 제품 경쟁력 확보', '국내 최초 코로나19 백신 품목허가로 국내외 백신 시장 진출 기반 마련 및 브랜드 신뢰도 제고', '글로벌 탑티어 바이오 기업으로 성장 가속화 기대'] negative_stocks=[] negative_keywords=[] negative_reasons=[]"
4,2022-07-01 21:48:04,economy,경향신문,금융당국 “증시 변동성 완화 조치”,4일부터 석달간 증권사 신용융자담보비율 유지의무 면제 금융당국이 코스피지수가 장중 2300 아래까지 떨어지자 주식시장 변동성을 완화하는 조치를 시행하기로 했다. 금융위원회는 1일 주식시장 마감 후 김소영 부위원장 주재로 증권 유관기관과 금융시장합동점검회의를 열고 변동성 완화조치를 시행하기로 했다고 밝혔다. 이에 따라 다음 주식시장 개장일인 오는 4일부터 9월30일까지 3개월간 증권사의 신용융자담보비율 유지의무가 면제된다. 신용융자담보비율 유지의무란 증권사가 일명 ‘빚투’ 빚내서 투자 자금인 신용융자를 시행할 때 담보를 140% 이상 확보하고 내규에서 정한 담보비율을 유지할 것을 요구하는 규제다. 유지의무 면제는 증권사의 신용융자 담보주식에 대한 과도한 반대매매를 억제하기 위한 조치다. 금융당국은 코로나19 사태가 본격화한 2020년 3월에도 이 같은 조치를 6개월간 시행한 바 있다. 7일부터 10월6일까지는 상장기업의 하루 자기주식 매수 주문 수량 한도 제한도 완화된다. 신탁취득 주식도 발행주식총수의 1% 이내에서 신탁재산 총액 범위 내로 한시적으로 확대된다. 이와 함께 금융위는 금융감독원과 한국거래소 합동으로 공매도 특별점검을 실시해 공매도 현황과 시장교란 가능성 등을 살펴보기로 했다. 현재 공매도는 지난해 5월 이후 제한적으로 실시되고 있다. 금융위와 금감원은 매주 금요일 금융시장합동점검회의를 열어 증시 등 금융시장상황을 점검할 예정이다. 금융당국은 “컨틴전시플랜에 따라 필요한 시장 변동성 완화 조치를 검토·시행해 나갈 것”이라고 말했다.,https://n.news.naver.com/mnews/article/032/0003157041?sid=101,"1일 1일 금융위원회는 증권 유관기관과 금융시장합동점검회의를 열고 코스피지수가 장중 2300 아래까지 떨어지자 주식시장 변동성을 완화하는 조치를 시행하기로 하였으며, 이에 따라 다음 주식시장 개장일인 오는 4일부터 9월30일까지 3개월간 증권사의 신용융자담보비율 유지의무가 면제된다.",금융당국 “증시 변동성 완화 조치”\n4일부터 석달간 증권사 신용융자담보비율 유지의무 면제 금융당국이 코스피지수가 장중 2300 아래까지 떨어지자 주식시장 변동성을 완화하는 조치를 시행하기로 했다. 금융위원회는 1일 주식시장 마감 후 김소영 부위원장 주재로 증권 유관기관과 금융시장합동점검회의를 열고 변동성 완화조치를 시행하기로 했다고 밝혔다. 이에 따라 다음 주식시장 개장일인 오는 4일부터 9월30일까지 3개월간 증권사의 신용융자담보비율 유지의무가 면제된다. 신용융자담보비율 유지의무란 증권사가 일명 ‘빚투’ 빚내서 투자 자금인 신용융자를 시행할 때 담보를 140% 이상 확보하고 내규에서 정한 담보비율을 유지할 것을 요구하는 규제다. 유지의무 면제는 증권사의 신용융자 담보주식에 대한 과도한 반대매매를 억제하기 위한 조치다. 금융당국은 코로나19 사태가 본격화한 2020년 3월에도 이 같은 조치를 6개월간 시행한 바 있다. 7일부터 10월6일까지는 상장기업의 하루 자기주식 매수 주문 수량 한도 제한도 완화된다. 신탁취득 주식도 발행주식총수의 1% 이내에서 신탁재산 총액 범위 내로 한시적으로 확대된다. 이와 함께 금융위는 금융감독원과 한국거래소 합동으로 공매도 특별점검을 실시해 공매도 현황과 시장교란 가능성 등을 살펴보기로 했다. 현재 공매도는 지난해 5월 이후 제한적으로 실시되고 있다. 금융위와 금감원은 매주 금요일 금융시장합동점검회의를 열어 증시 등 금융시장상황을 점검할 예정이다. 금융당국은 “컨틴전시플랜에 따라 필요한 시장 변동성 완화 조치를 검토·시행해 나갈 것”이라고 말했다.,"stock_related=False summary='금융당국이 최근 코스피지수 하락에 대응해 4일부터 9월30일까지 석달간 증권사의 신용융자담보비율 유지의무를 면제하는 등 증시 변동성 완화 조치를 시행한다. 또한 자기주식 매수 제한 완화, 신탁취득 주식 확대, 공매도 특별점검 실시 등 여러 대책을 도입하여 시장 안정화를 도모할 계획이다. 금융당국은 앞으로도 시장 상황에 따라 추가적인 변동성 완화 조치를 검토·시행할 예정이다.' positive_stocks=[] positive_keywords=[] positive_reasons=[] negative_stocks=[] negative_keywords=[] negative_reasons=[]"

In [14]:
# json 변환
# - Pydantic.BaseModel.model_dump() -> dict
# - Pydantic.BaseModel.model_dump_json() -> json_str

# Pydantic 객체를 JSON 문자열로 변환하는 함수
def parse_to_json(obj):
    return obj.model_dump_json()    # StockAnalysis 객체 -> JSON 문자열로 파싱

df['result_json'] = df['result'].apply(parse_to_json)   # result_json 컬럼은 JSON 문자열로 파싱한 결과
df.head()

,date,category,press,title,document,link,summary,content,result,result_json
0,2022-07-03 17:14:37,economy,YTN,추경호 중기 수출지원 총력 무역금융 40조 확대,앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 했습니다. 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했습니다. 류환홍 기자가 보도합니다. 기자 수출은 최고의 실적을 보였지만 수입액이 급증하면서 올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록했습니다. 정부가 수출확대에 총력을 기울이기로 한 것은 원자재 가격 상승 등 대외 리스크가 가중되는 상황에서 수출 증가세 지속이야말로 한국경제의 회복을 위한 열쇠라고 본 것입니다. 추경호 경제부총리 겸 기획재정부 장관 정부는 우리 경제의 성장엔진인 수출이 높은 증가세를 지속할 수 있도록 총력을 다하겠습니다. 우선 물류 부담 증가 원자재 가격 상승 등 가중되고 있는 대외 리스크에 대해 적극 대응하겠습니다. 특히 중소기업과 중견기업 수출 지원을 위해 무역금융 규모를 연초 목표보다 40조 원 늘린 301조 원까지 확대하고 물류비 부담을 줄이기 위한 대책도 마련했습니다. 이창양 산업통상자원부 장관 국제 해상운임이 안정될 때까지 월 4척 이상의 임시선박을 지속 투입하는 한편 중소기업 전용 선복 적재 용량 도 현재보다 주당 50TEU 늘려 공급하겠습니다. 하반기에 우리 기업들의 수출 기회를 늘리기 위해 2 500여 개 수출기업을 대상으로 해외 전시회 참가를 지원하는 등 마케팅 지원도 벌이기로 했습니다. 정부는 또 이달 중으로 반도체를 비롯한 첨단 산업 육성 전략을 마련해 수출 증가세를 뒷받침하고 에너지 소비를 줄이기 위한 효율화 방안을 마련해 무역수지 개선에 나서기로 했습니다. YTN 류환홍입니다.,https://n.news.naver.com/mnews/article/052/0001759333?sid=101,"올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록한 가운데, 정부가 하반기에 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 결정한 가운데, 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했다.",추경호 중기 수출지원 총력 무역금융 40조 확대\n앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 했습니다. 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했습니다. 류환홍 기자가 보도합니다. 기자 수출은 최고의 실적을 보였지만 수입액이 급증하면서 올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록했습니다. 정부가 수출확대에 총력을 기울이기로 한 것은 원자재 가격 상승 등 대외 리스크가 가중되는 상황에서 수출 증가세 지속이야말로 한국경제의 회복을 위한 열쇠라고 본 것입니다. 추경호 경제부총리 겸 기획재정부 장관 정부는 우리 경제의 성장엔진인 수출이 높은 증가세를 지속할 수 있도록 총력을 다하겠습니다. 우선 물류 부담 증가 원자재 가격 상승 등 가중되고 있는 대외 리스크에 대해 적극 대응하겠습니다. 특히 중소기업과 중견기업 수출 지원을 위해 무역금융 규모를 연초 목표보다 40조 원 늘린 301조 원까지 확대하고 물류비 부담을 줄이기 위한 대책도 마련했습니다. 이창양 산업통상자원부 장관 국제 해상운임이 안정될 때까지 월 4척 이상의 임시선박을 지속 투입하는 한편 중소기업 전용 선복 적재 용량 도 현재보다 주당 50TEU 늘려 공급하겠습니다. 하반기에 우리 기업들의 수출 기회를 늘리기 위해 2 500여 개 수출기업을 대상으로 해외 전시회 참가를 지원하는 등 마케팅 지원도 벌이기로 했습니다. 정부는 또 이달 중으로 반도체를 비롯한 첨단 산업 육성 전략을 마련해 수출 증가세를 뒷받침하고 에너지 소비를 줄이기 위한 효율화 방안을 마련해 무역수지 개선에 나서기로 했습니다. YTN 류환홍입니다.,"stock_related=True summary='정부가 수출 확대를 위해 무역금융 규모를 40조 원 이상 확대하고, 물류비 지원과 임시선박 투입 등 수출 중소기업 지원 대책을 추진키로 했습니다. 또한 반도체 등 첨단 산업 육성 전략과 에너지 효율화 방안도 마련해 무역수지 개선에 나설 계획입니다.' positive_stocks=['삼성전자', 'SK하이닉스', '현대글로비스', '팬오션'] positive_keywords=['무역금융 확대', '물류비 지원', '임시선박 투입', '첨단산업 육성', '수출 확대'] positive_reasons=['무역금융 확대와 물류비 절감 대책은 수출 중소기업의 경쟁력 강화에 긍정적 영향', '임시선박 투입으로 물류난 해소 기대', '반도체 등 첨단 산업 육성 전략은 수출 주도 산업 강화와 관련주에 긍정적', '현대글로비스, 팬오션 등 물류 관련 기업은 물류 지원 정책 수혜 예상'] negative_stocks=[] negative_keywords=[] negative_reasons=[]","{""stock_related"":true,""summary"":""정부가 수출 확대를 위해 무역금융 규모를 40조 원 이상 확대하고, 물류비 지원과 임시선박 투입 등 수출 중소기업 지원 대책을 추진키로 했습니다. 또한 반도체 등 첨단 산업 육성 전략과 에너지 효율화 방안도 마련해 무역수지 개선에 나설 계획입니다."",""positive_stocks"":[""삼성전자"",""SK하이닉스"",""현대글로비스"",""팬오션""],""positive_keywords"":[""무역금융 확대"",""물류비 지원"",""임시선박 투입"",""첨단산업 육성"",""수출 확대""],""positive_reasons"":[""무역금융 확대와 물류비 절감 대책은 수출 중소기업의 경쟁력 강화에 긍정적 영향"",""임시선박 투입으로 물류난 해소 기대"",""반도체 등 첨단 산업 육성 전략은 수출 주도 산업 강화와 관련주에 긍정적"",""현대글로비스, 팬오션 등 물류 관련 기업은 물류 지원 정책 수혜 예상""],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
1,2022-07-04 08:07:12,economy,아시아경제,해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다,문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준비 7 8월 2만5000원 추가 시 와인 5종 및 생맥주 무제한 제공 인터컨티넨탈 서울 코엑스 브래서리 쿨 섬머 페스타 . 인터컨티넨탈 서울 코엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타 를 진행한다고 4일 밝혔다. 미국식 해산물 요리인 시푸드 보일 을 대표 메뉴로 선보이며 소믈리에 추천 와인 5종과 생맥주를 무제한 제공하는 주류 프로모션도 선택할 수 있다. 시푸드 보일 이 대표 메뉴로 준비되고 라이브 스테이션에서 셰프가 직접 원하는 메뉴를 먹기 좋게 잘라 제공한다. 시푸드 보일은 문어와 랍스터 대게 갑오징어 새우 소라 관자 낙지 등 해산물을 쪄낸 뒤 셰프의 비법 시즈닝으로 이국적인 감칠맛을 더한 메뉴다. 프로모션 기간에는 해물전 가리비 불도장 장어 데마끼 로제 해물 뇨끼 등 한식 중식 일식 양식 등 세계 각국의 해산물 메뉴도 즐길 수 있다. 소믈리에 추천 와인 5종과 생맥주를 무제한으로 제공하는 옵션도 선택할 수 있다. 제공되는 와인은 레드와 화이트 와인 각 2종 스파클링 와인 1종으로 취향에 따라 다양하게 즐길 수 있다. 해당 기간 동안 입구 와인셀렉션 코너에서 10만원 이상 와인 구매 시 호텔에서 제작한 주트백도 선물로 증정한다. 이용 가격은 이전과 동일하며 네이버 예약 시 10% 할인 혜택도 제공한다. 주류 무제한 혜택은 2만5000원 추가 시 이용할 수 있다.,https://n.news.naver.com/mnews/article/277/0005112302?sid=101,인터엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타 를 진행하는데 미국식 해산물 요리인 시푸드 보일 을 대표 메뉴로 선보이며 소믈리에 추천 와인 5종과 생맥주를 무제한 제공하는 주류 프로모션도 선택할 수 있으며 프로모션 기간에는 해물전 가리비 불도장 장어 데마끼 로제 해물 뇨끼 등 한식 중식 일식 양식 등 세계 각국의 해산물 메뉴도 즐길 수 있다.,해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다\n문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준비 7 8월 2만5000원 추가 시 와인 5종 및 생맥주 무제한 제공 인터컨티넨탈 서울 코엑스 브래서리 쿨 섬머 페스타 . 인터컨티넨탈 서울 코엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타 를 진행한다고 4일 밝혔다. 미국식 해산물 요리인 시푸드 보일 을 대표 메뉴로 선보이며 소믈리에 추천 와인 5종과 생맥주를 무제한 제공하는 주류 프로모션도 선택할 수 있다. 시푸드 보일 이 대표 메뉴로 준비되고 라이브 스테이션에서 셰프가 직접 원하는 메뉴를 먹기 좋게 잘라 제공한다. 시푸드 보일은 문어와 랍스터 대게 갑오징어 새우 소라 관자 낙지 등 해산물을 쪄낸 뒤 셰프의 비법 시즈닝으로 이국적인 감칠맛을 더한 메뉴다. 프로모션 기간에는 해물전 가리비 불도장 장어 데마끼 로제 해물 뇨끼 등 한식 중식 일식 양식 등 세계 각국의 해산물 메뉴도 즐길 수 있다. 소믈리에 추천 와인 5종과 생맥주를 무제한으로 제공하는 옵션도 선택할 수 있다. 제공되는 와인은 레드와 화이트 와인 각 2종 스파클링 와인 1종으로 취향에 따라 다양하게 즐길 수 있다. 해당 기간 동안 입구 와인셀렉션 코너에서 10만원 이상 와인 구매 시 호텔에서 제작한 주트백도 선물로 증정한다. 이용 가격은 이전과 동일하며 네이버 예약 시 10% 할인 혜택도 제공한다. 주류 무제한 혜택은 2만5000원 추가 시 이용할 수 있다.,"stock_related=False summary=""인터컨티넨탈 서울 코엑스 뷔페 레스토랑이 여름 한정으로 '쿨 섬머 페스타'를 진행한다. 주요 메뉴로 시푸드 보일(미국식 해산물 찜)을 선보이고, 문어, 랍스터, 대게 등 다양한 해산물을 활용한다. 7~8월 동안 2만5000원 추가 시 와인 5종과 생맥주를 무제한으로 제공하는 주류 프로모션을 선택할 수 있다. 다양한 해산물 요리와 세계 각국의 메뉴도 즐길 수 있으며, 네이버 예약 할인 혜택과 와인 구매 시 주트백 증정 이벤트도 있다."" positive_stocks=[] positive_keywords=[] positive_reasons=[] negative_stocks=[] negative_keywords=[] negative_reasons=[]","{""stock_related"":false,""summary"":""인터컨티넨탈 서울 코엑스 뷔페 레스토랑이 여름 한정으로 '쿨 섬머 페스타'를 진행한다. 주요 메뉴로 시푸드 보일(미국식 해산물 찜)을 선보이고, 문어, 랍스터, 대게 등 다양한 해산물을 활용한다. 7~8월 동안 2만5000원 추가 시 와인 5종과 생맥주를 무제한으로 제공하는 주류 프로모션을 선택할 수 있다. 다양한 해산물 요리와 세계 각국의 메뉴도 즐길 수 있으며, 네이버 예약 할인 혜택과 와인 구매 시 주트백 증정 이벤트도 있다."",""positive_stocks"":[],""positive_keywords"":[],""positive_reasons"":[],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
2,2022-07-01 08:51:12,economy,뉴시스,에디슨이노 이승훈 제이스페이스 대표 사내이사 선임,기사내용 요약 우주발사체 사업 본격화 서울 뉴시스 김경택 기자 에디슨이노가 우주발사체 사업에 본격 진출한다고 1일 밝혔다. 에디슨이노는 전날 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이스홀딩스 대표이사를 사내이사로 선임했다. 이날 사업 목적에 위성체 발사와 우주선 위성시스템 등 항공 우주 분야와 자율 주행·그래핀 관련 사업을 사업목적에 추가했다. 사내이사에 이승영 카이스트 정밀기계공학 박사를 영입해 임플란트 관련 연구·생산기술을 보강했다. 서울대 화학생물공학 출신 최도영 씨도 선임해 현재 임상 시험계획 승인을 받은 생체흡수성 금속 리조멧 사업 확대를 도모한다 계획이다. 골절 수술 시 인체에 흡수되는 소재인 리조멧은 국내 임상 계획 승인과 중국 내 임상승인에 요구되는 시험을 통과한 상태다.,https://n.news.naver.com/mnews/article/003/0011279060?sid=101,에디슨이노는 1일 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이스홀딩스 대표이사를 사내이사로 선임하고 위성체 발사와 우주선 위성시스템 등 항공 우주 분야와 자율 주행·그래핀 관련 사업을 사업목적에 추가하여 우주발사체 사업에 본격 진출한다고 1일 밝혔다.,에디슨이노 이승훈 제이스페이스 대표 사내이사 선임\n기사내용 요약 우주발사체 사업 본격화 서울 뉴시스 김경택 기자 에디슨이노가 우주발사체 사업에 본격 진출한다고 1일 밝혔다. 에디슨이노는 전날 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이스홀딩스 대표이사를 사내이사로 선임했다. 이날 사업 목적에 위성체 발사와 우주선 위성시스템 등 항공 우주 분야와 자율 주행·그래핀 관련 사업을 사업목적에 추가했다. 사내이사에 이승영 카이스트 정밀기계공학 박사를 영입해 임플란트 관련 연구·생산기술을 보강했다. 서울대 화학생물공학 출신 최도영 씨도 선임해 현재 임상 시험계획 승인을 받은 생체흡수성 금속 리조멧 사업 확대를 도모한다 계획이다. 골절 수술 시 인체에 흡수되는 소재인 리조멧은 국내 임상 계획 승인과 중국 내 임상승인에 요구되는 시험을 통과한 상태다.,"stock_related=True summary='에디슨이노는 이노시스로 사명을 변경하고 우주발사체 및 위성시스템 등 항공우주 사업에 본격 진출한다. 이승훈 제이스페이스홀딩스 대표를 사내이사로 선임하며 우주 분야 역량을 강화했다. 또한 임플란트 연구개발과 생체흡수성 금속 리조멧 사업도 확장할 계획이다.' positive_stocks=['에디슨이노'] positive_keywords=['우주발사체', '항공우주 사업 진출', '사내이사 선임', '위성시스템', '생체흡수성 금속 리조멧'] positive_reasons=['우주발사체와 위성시스템 등 신사업 진출로 성장 동력 확보', '제이스페이스홀딩스 대표 선임을 통한 전문성 강화', '임플란트 및 생체흡수성 금속 사업 확대가 추가 성장 기대요인'] negative_stocks=[] negative_keywords=[] negative_reasons=[]","{""stock_related"":true,""summary"":""에디슨이노는 이노시스로 사명을 변경하고 우주발사체 및 위성시스템 등 항공우주 사업에 본격 진출한다. 이승훈 제이스페이스홀딩스 대표를 사내이사로 선임하며 우주 분야 역량을 강화했다. 또한 임플란트 연구개발과 생체흡수성 금속 리조멧 사업도 확장할 계획이다."",""positive_stocks"":[""에디슨이노""],""positive_keywords"":[""우주발사체"",""항공우주 사업 진출"",""사내이사 선임"",""위성시스템"",""생체흡수성 금속 리조멧""],""positive_reasons"":[""우주발사체와 위성시스템 등 신사업 진출로 성장 동력 확보"",""제이스페이스홀딩스 대표 선임을 통한 전문성 강화"",""임플란트 및 생체흡수성 금속 사업 확대가 추가 성장 기대요인""],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
3,2022-07-01 16:11:01,economy,머니투데이,SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차,SK바이오사이언스가 글로벌 사업의 고도화를 위해 조직 개편을 단행했다. SK바이오사이언스는 기존 해외사업개발실을 BD Business Development 1 3실로 확대 재편하고 글로벌 규제 및 허가 전담 조직인 Global RA Regulatory Affairs 실을 신설한다고 1일 밝혔다. SK바이오사이언스는 지난해 코로나19 COVID 19 백신 위탁 생산 등으로 주목받는 백신 기업으로 부상하며 글로벌 사업의 영역과 규모가 급속도로 성장 중이다. 이러한 성장 속도에 맞춰 기존 전담 조직인 해외사업개발실을 보다 세분화 및 전문화하고자 BD 1 3실로 확대 재편했다. BD 1 3실은 앞으로 기존에 영위 중인 백신 사업뿐만 아니라 세포·유전자치료제 CGT 등 신규 사업에 대한 △글로벌 네트워크들과의 공동 개발 △신규 C D MO 수주 △개발 제품 상업화 등 다양한 영역의 사업을 고도화하고 실행력을 높이는 업무를 담당한다. 또한 Global RA실을 신설해 미국 유럽 등 해외 선진국의 GMP Good Manufacturing Practice 를 확보하는 등 국제적인 수준의 관련 인증 및 허가 획득에도 더욱 박차를 가할 방침이다. CMC팀도 신설됐다. CMC는 화학 Chemistry 제조 Manufacturing 품질 Control 의 약자다. CMC팀은 완제 의약품을 만드는 공정 개발 process development 과 품질 관리 quality control 부문에서 핵심적인 역할을 수행한다. 연구부터 임상 허가 생산 품질에 이르는 GMP 관련 제반 업무를 관리한다. SK바이오사이언스는 이번 조직 개편이 글로벌 탑티어 바이오 기업으로의 성장을 더욱 앞당기고 초격차 경쟁력 확보의 계기가 될 것으로 기대하고 있다. SK바이오사이언스는 지난달 29일 국내 최초 코로나19 백신인 스카이코비원 SKYCovione 멀티주 의 품목허가를 획득했다. 이어 국가출하승인 및 WHO 등 해외 승인을 통해 국내외 백신 시장에 본격 진출할 예정이다.,https://n.news.naver.com/mnews/article/008/0004765787?sid=101,SK바이오사이언스가 글로벌 사업의 고도화를 위해 기존 해외사업개발실을 백신사업뿐만 아니라 다양한 영역의 사업을 고도화하고 실행력을 높이는 업무를 담당하는 1 3실로 확대 재편하고 글로벌 규제 및 허가 전담 조직을 신설한다고 1일 밝혔다.,SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차\nSK바이오사이언스가 글로벌 사업의 고도화를 위해 조직 개편을 단행했다. SK바이오사이언스는 기존 해외사업개발실을 BD Business Development 1 3실로 확대 재편하고 글로벌 규제 및 허가 전담 조직인 Global RA Regulatory Affairs 실을 신설한다고 1일 밝혔다. SK바이오사이언스는 지난해 코로나19 COVID 19 백신 위탁 생산 등으로 주목받는 백신 기업으로 부상하며 글로벌 사업의 영역과 규모가 급속도로 성장 중이다. 이러한 성장 속도에 맞춰 기존 전담 조직인 해외사업개발실을 보다 세분화 및 전문화하고자 BD 1 3실로 확대 재편했다. BD 1 3실은 앞으로 기존에 영위 중인 백신 사업뿐만 아니라 세포·유전자치료제 CGT 등 신규 사업에 대한 △글로벌 네트워크들과의 공동 개발 △신규 C D MO 수주 △개발 제품 상업화 등 다양한 영역의 사업을 고도화하고 실행력을 높이는 업무를 담당한다. 또한 Global RA실을 신설해 미국 유럽 등 해외 선진국의 GMP Good Manufacturing Practice 를 확보하는 등 국제적인 수준의 관련 인증 및 허가 획득에도 더욱 박차를 가할 방침이다. CMC팀도 신설됐다. CMC는 화학 Chemistry 제조 Manufacturing 품질 Control 의 약자다. CMC팀은 완제 의약품을 만드는 공정 개발 process development 과 품질 관리 quality control 부문에서 핵심적인 역할을 수행한다. 연구부터 임상 허가 생산 품질에 이르는 GMP 관련 제반 업무를 관리한다. SK바이오사이언스는 이번 조직 개편이 글로벌 탑티어 바이오 기업으로의 성장을 더욱 앞당기고 초격차 경쟁력 확보의 계기가 될 것으로 기대하고 있다. SK바이오사이언스는 지난달 29일 국내 최초 코로나19 백신인 스카이코비원 SKYCovione 멀티주 의 품목허가를 획득했다. 이어 국가출하승인 및 WHO 등 해외 승인을 통해 국내외 백신 시장에 본격 진출할 예정이다.,"stock_related=True summary='SK바이오사이언스는 글로벌 사업의 고도화를 위해 해외사업 조직을 BD 1-3실로 세분화하고, 글로벌 규제 및 허가 전담 조직인 Global RA실과 의약품 공정개발 및 품질관리 담당 CMC팀을 신설했다. 코로나19 백신 위탁생산을 통해 급성장한 동사는 이번 조직개편으로 글로벌 백신 시장 진출과 세포·유전자치료제 등 신규 사업 고도화에 박차를 가하고 있으며, 국내 최초 코로나19 백신 품목허가를 획득해 시장 경쟁력을 강화하고 있다.' positive_stocks=['SK바이오사이언스'] positive_keywords=['글로벌 사업 고도화', '조직 개편', '백신 사업 확장', '신규 사업', '규제 및 허가 전담 조직', 'CMC팀 신설', '코로나19 백신 품목허가'] positive_reasons=['조직 개편으로 글로벌 네트워크와 공동 개발 및 신규 수주가 강화되어 사업 실행력이 높아짐', 'Global RA실 신설로 미국, 유럽 등 선진국 GMP 인증 및 허가 획득 탄력 전망', 'CMC팀 신설로 공정 개발과 품질 관리 강화되어 제품 경쟁력 확보', '국내 최초 코로나19 백신 품목허가로 국내외 백신 시장 진출 기반 마련 및 브랜드 신뢰도 제고', '글로벌 탑티어 바이오 기업으로 성장 가속화 기대'] negative_stocks=[] negative_keywords=[] negative_reasons=[]","{""stock_related"":true,""summary"":""SK바이오사이언스는 글로벌 사업의 고도화를 위해 해외사업 조직을 BD 1-3실로 세분화하고, 글로벌 규제 및 허가 전담 조직인 Global RA실과 의약품 공정개발 및 품질관리 담당 CMC팀을 신설했다. 코로나19 백신 위탁생산을 통해 급성장한 동사는 이번 조직개편으로 글로벌 백신 시장 진출과 세포·유전자치료제 등 신규 사업 고도화에 박차를 가하고 있으며, 국내 최초 코로나19 백신 품목허가를 획득해 시장 경쟁력을 강화하고 있다."",""positive_stocks"":[""SK바이오사이언스""],""positive_keywords"":[""글로벌 사업 고도화"",""조직 개편"",""백신 사업 확장"",""신규 사업"",""규제 및 허가 전담 조직"",""CMC팀 신설"",""코로나19 백신 품목허가""],""positive_reasons"":[""조직 개편으로 글로벌 네트워크와 공동 개발 및 신규 수주가 강화되어 사업 실행력이 높아짐"",""Global RA실 신설로 미국, 유럽 등 선진국 GMP 인증 및 허가 획득 탄력 전망"",""CMC팀 신설로 공정 개발과 품질 관리 강화되어 제품 경쟁력 확보"",""국내 최초 코로나19 백신 품목허가로 국내외 백신 시장 진출 기반 마련 및 브랜드 신뢰도 제고"",""글로벌 탑티어 바이오 기업으로 성장 가속화 기대""],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
4,2022-07-01 21:48:04,economy,경향신문,금융당국 “증시 변동성 완화 조치”,4일부터 석달간 증권사 신용융자담보비율 유지의무 면제 금융당국이 코스피지수가 장중 2300 아래까지 떨어지자 주식시장 변동성을 완화하는 조치를 시행하기로 했다. 금융위원회는 1일 주식시장 마감 후 김소영 부위원장 주재로 증권 유관기관과 금융시장합동점검회의를 열고 변동성 완화조치를 시행하기로 했다고 밝혔다. 이에 따라 다음 주식시장 개장일인 오는 4일부터 9월30일까지 3개월간 증권사의 신용융자담보비율 유지의무가 면제된다. 신용융자담보비율 유지의무란 증권사가 일명 ‘빚투’ 빚내서 투자 자금인 신용융자를 시행할 때 담보를 140% 이상 확보하고 내규에서 정한 담보비율을 유지할 것을 요구하는 규제다. 유지의무 면제는 증권사의 신용융자 담보주식에 대한 과도한 반대매매를 억제하기 위한 조치다. 금융당국은 코로나19 사태가 본격화한 2020년 3월에도 이 같은 조치를 6개월간 시행한 바 있다. 7일부터 10월6일까지는 상장기업의 하루 자기주식 매수 주문 수량 한도 제한도 완화된다. 신탁취득 주식도 발행주식총수의 1% 이내에서 신탁재산 총액 범위 내로 한시적으로 확대된다. 이와 함께 금융위는 금융감독원과 한국거래소 합동으로 공매도 특별점검을 실시해 공매도 현황과 시장교란 가능성 등을 살펴보기로 했다. 현재 공매도는 지난해 5월 이후 제한적으로 실시되고 있다. 금융위와 금감원은 매주 금요일 금융시장합동점검회의를 열어 증시 등 금융시장상황을 점검할 예정이다. 금융당국은 “컨틴전시플랜에 따라 필요한 시장 변동성 완화 조치를 검토·시행해 나갈 것”이라고 말했다.,https://n.news.naver.com/mnews/article/032/0003157041?sid=101,"1일 1일 금융위원회는 증권 유관기관과 금융시장합동점검회의를 열고 코스피지수가 장중 2300 아래까지 떨어지자 주식시장 변동성을 완화하는 조치를 시행하기로 하였으며, 이에 따라 다음 주식시장 개장일인 오는 4일부터 9월30일까지 3개월간 증권사의 신용융자담보비율 유지의무가 면제된다.",금융당국 “증시 변동성 완화 조치”\n4일부터 석달간 증권사 신용융자담보비율 유지의무 면제 금융당국이 코스피지수가 장중 2300 아래까지 떨어지자 주식시장 변동성을 완화하는 조치를 시행하기로 했다. 금융위원회는 1일 주식시장 마감 후 김소영 부위원장 주재로 증권 유관기관과 금융시장합동점검회의를 열고 변동성 완화조치를 시행하기로 했다고 밝혔다. 이에 따라 다음 주식시장 개장일인 오는 4일부터 9월30일까지 3개월간 증권사의 신용융자담보비율 유지의무가 면제된다. 신용융자담보비율 유지의무란 증권사가 일명 ‘빚투’ 빚내서 투자 자금인 신용융자를 시행할 때 담보를 140% 이상 확보하고 내규에서 정한 담보비율을 유지할 것을 요구하는 규제다. 유지의무 면제는 증권사의 신용융자 담보주식에 대한 과도한 반대매매를 억제하기 위한 조치다. 금융당국은 코로나19 사태가 본격화한 2020년 3월에도 이 같은 조치를 6개월간 시행한 바 있다. 7일부터 10월6일까지는 상장기업의 하루 자기주식 매수 주문 수량 한도 제한도 완화된다. 신탁취득 주식도 발행주식총수의 1% 이내에서 신탁재산 총액 범위 내로 한시적으로 확대된다. 이와 함께 금융위는 금융감독원과 한국거래소 합동으로 공매도 특별점검을 실시해 공매도 현황과 시장교란 가능성 등을 살펴보기로 했다. 현재 공매도는 지난해 5월 이후 제한적으로 실시되고 있다. 금융위와 금감원은 매주 금요일 금융시장합동점검회의를 열어 증시 등 금융시장상황을 점검할 예정이다. 금융당국은 “컨틴전시플랜에 따라 필요한 시장 변동성 완화 조치를 검토·시행해 나갈 것”이라고 말했다.,"stock_related=False summary='금융당국이 최근 코스피지수 하락에 대응해 4일부터 9월30일까지 석달간 증권사의 신용융자담보비율 유지의무를 면제하는 등 증시 변동성 완화 조치를 시행한다. 또한 자기주식 매수 제한 완화, 신탁취득 주식 확대, 공매도 특별점검 실시 등 여러 대책을 도입하여 시장 안정화를 도모할 계획이다. 금융당국은 앞으로도 시장 상황에 따라 추가적인 변동성 완화 조치를 검토·시행할 예정이다.' positive_stocks=[] positive_keywords=[] positive_reasons=[] negative_stocks=[] negative_keywords=[] negative_reasons=[]","{""stock_related"":false,""summary"":""금융당국이 최근 코스피지수 하락에 대응해 4일부터 9월30일까지 석달간 증권사의 신용융자담보비율 유지의무를 면제하는 등 증시 변동성 완화 조치를 시행한다. 또한 자기주식 매수 제한 완화, 신탁취득 주식 확대, 공매도 특별점검 실시 등 여러 대책을 도입하여 시장 안정화를 도모할 계획이다. 금융당국은 앞으로도 시장 상황에 따라 추가적인 변동성 완화 조치를 검토·시행할 예정이다."",""positive_stocks"":[],""positive_keywords"":[],""positive_reasons"":[],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"

In [15]:
df['system'] = system_prompt

df = df.rename(columns={
    'content' : 'user',    
    'result_json' : 'assistant'
})

df[['system', 'user', 'assistant']]

,system,user,assistant
0,"# 모델 역할/출력 규칙을 고정하는 시스템 프롬프트\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n - stock_related를 False로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n - stock_related를 True로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n",추경호 중기 수출지원 총력 무역금융 40조 확대\n앵커 정부가 올해 하반기 우리 경제의 버팀목인 수출 확대를 위해 총력을 기울이기로 했습니다. 특히 수출 중소기업의 물류난 해소를 위해 무역금융 규모를 40조 원 이상 확대하고 물류비 지원과 임시선박 투입 등을 추진하기로 했습니다. 류환홍 기자가 보도합니다. 기자 수출은 최고의 실적을 보였지만 수입액이 급증하면서 올해 상반기 우리나라 무역수지는 역대 최악인 103억 달러 적자를 기록했습니다. 정부가 수출확대에 총력을 기울이기로 한 것은 원자재 가격 상승 등 대외 리스크가 가중되는 상황에서 수출 증가세 지속이야말로 한국경제의 회복을 위한 열쇠라고 본 것입니다. 추경호 경제부총리 겸 기획재정부 장관 정부는 우리 경제의 성장엔진인 수출이 높은 증가세를 지속할 수 있도록 총력을 다하겠습니다. 우선 물류 부담 증가 원자재 가격 상승 등 가중되고 있는 대외 리스크에 대해 적극 대응하겠습니다. 특히 중소기업과 중견기업 수출 지원을 위해 무역금융 규모를 연초 목표보다 40조 원 늘린 301조 원까지 확대하고 물류비 부담을 줄이기 위한 대책도 마련했습니다. 이창양 산업통상자원부 장관 국제 해상운임이 안정될 때까지 월 4척 이상의 임시선박을 지속 투입하는 한편 중소기업 전용 선복 적재 용량 도 현재보다 주당 50TEU 늘려 공급하겠습니다. 하반기에 우리 기업들의 수출 기회를 늘리기 위해 2 500여 개 수출기업을 대상으로 해외 전시회 참가를 지원하는 등 마케팅 지원도 벌이기로 했습니다. 정부는 또 이달 중으로 반도체를 비롯한 첨단 산업 육성 전략을 마련해 수출 증가세를 뒷받침하고 에너지 소비를 줄이기 위한 효율화 방안을 마련해 무역수지 개선에 나서기로 했습니다. YTN 류환홍입니다.,"{""stock_related"":true,""summary"":""정부가 수출 확대를 위해 무역금융 규모를 40조 원 이상 확대하고, 물류비 지원과 임시선박 투입 등 수출 중소기업 지원 대책을 추진키로 했습니다. 또한 반도체 등 첨단 산업 육성 전략과 에너지 효율화 방안도 마련해 무역수지 개선에 나설 계획입니다."",""positive_stocks"":[""삼성전자"",""SK하이닉스"",""현대글로비스"",""팬오션""],""positive_keywords"":[""무역금융 확대"",""물류비 지원"",""임시선박 투입"",""첨단산업 육성"",""수출 확대""],""positive_reasons"":[""무역금융 확대와 물류비 절감 대책은 수출 중소기업의 경쟁력 강화에 긍정적 영향"",""임시선박 투입으로 물류난 해소 기대"",""반도체 등 첨단 산업 육성 전략은 수출 주도 산업 강화와 관련주에 긍정적"",""현대글로비스, 팬오션 등 물류 관련 기업은 물류 지원 정책 수혜 예상""],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
1,"# 모델 역할/출력 규칙을 고정하는 시스템 프롬프트\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n - stock_related를 False로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n - stock_related를 True로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n",해산물·주류 무제한 인터컨티넨탈 뷔페 여름 한정 페스타 연다\n문어 랍스터 대게 갑오징어 새우 소라 등 해산물 활용 미국식 해물찜 시푸드 보일 준비 7 8월 2만5000원 추가 시 와인 5종 및 생맥주 무제한 제공 인터컨티넨탈 서울 코엑스 브래서리 쿨 섬머 페스타 . 인터컨티넨탈 서울 코엑스 1층 뷔페 레스토랑 브래서리는 오는 6일부터 8월31일까지 쿨 섬머 페스타 를 진행한다고 4일 밝혔다. 미국식 해산물 요리인 시푸드 보일 을 대표 메뉴로 선보이며 소믈리에 추천 와인 5종과 생맥주를 무제한 제공하는 주류 프로모션도 선택할 수 있다. 시푸드 보일 이 대표 메뉴로 준비되고 라이브 스테이션에서 셰프가 직접 원하는 메뉴를 먹기 좋게 잘라 제공한다. 시푸드 보일은 문어와 랍스터 대게 갑오징어 새우 소라 관자 낙지 등 해산물을 쪄낸 뒤 셰프의 비법 시즈닝으로 이국적인 감칠맛을 더한 메뉴다. 프로모션 기간에는 해물전 가리비 불도장 장어 데마끼 로제 해물 뇨끼 등 한식 중식 일식 양식 등 세계 각국의 해산물 메뉴도 즐길 수 있다. 소믈리에 추천 와인 5종과 생맥주를 무제한으로 제공하는 옵션도 선택할 수 있다. 제공되는 와인은 레드와 화이트 와인 각 2종 스파클링 와인 1종으로 취향에 따라 다양하게 즐길 수 있다. 해당 기간 동안 입구 와인셀렉션 코너에서 10만원 이상 와인 구매 시 호텔에서 제작한 주트백도 선물로 증정한다. 이용 가격은 이전과 동일하며 네이버 예약 시 10% 할인 혜택도 제공한다. 주류 무제한 혜택은 2만5000원 추가 시 이용할 수 있다.,"{""stock_related"":false,""summary"":""인터컨티넨탈 서울 코엑스 뷔페 레스토랑이 여름 한정으로 '쿨 섬머 페스타'를 진행한다. 주요 메뉴로 시푸드 보일(미국식 해산물 찜)을 선보이고, 문어, 랍스터, 대게 등 다양한 해산물을 활용한다. 7~8월 동안 2만5000원 추가 시 와인 5종과 생맥주를 무제한으로 제공하는 주류 프로모션을 선택할 수 있다. 다양한 해산물 요리와 세계 각국의 메뉴도 즐길 수 있으며, 네이버 예약 할인 혜택과 와인 구매 시 주트백 증정 이벤트도 있다."",""positive_stocks"":[],""positive_keywords"":[],""positive_reasons"":[],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
2,"# 모델 역할/출력 규칙을 고정하는 시스템 프롬프트\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n - stock_related를 False로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n - stock_related를 True로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n",에디슨이노 이승훈 제이스페이스 대표 사내이사 선임\n기사내용 요약 우주발사체 사업 본격화 서울 뉴시스 김경택 기자 에디슨이노가 우주발사체 사업에 본격 진출한다고 1일 밝혔다. 에디슨이노는 전날 임시주주총회를 통해 사명을 이노시스 로 변경하고 이승훈 제이스페이스홀딩스 대표이사를 사내이사로 선임했다. 이날 사업 목적에 위성체 발사와 우주선 위성시스템 등 항공 우주 분야와 자율 주행·그래핀 관련 사업을 사업목적에 추가했다. 사내이사에 이승영 카이스트 정밀기계공학 박사를 영입해 임플란트 관련 연구·생산기술을 보강했다. 서울대 화학생물공학 출신 최도영 씨도 선임해 현재 임상 시험계획 승인을 받은 생체흡수성 금속 리조멧 사업 확대를 도모한다 계획이다. 골절 수술 시 인체에 흡수되는 소재인 리조멧은 국내 임상 계획 승인과 중국 내 임상승인에 요구되는 시험을 통과한 상태다.,"{""stock_related"":true,""summary"":""에디슨이노는 이노시스로 사명을 변경하고 우주발사체 및 위성시스템 등 항공우주 사업에 본격 진출한다. 이승훈 제이스페이스홀딩스 대표를 사내이사로 선임하며 우주 분야 역량을 강화했다. 또한 임플란트 연구개발과 생체흡수성 금속 리조멧 사업도 확장할 계획이다."",""positive_stocks"":[""에디슨이노""],""positive_keywords"":[""우주발사체"",""항공우주 사업 진출"",""사내이사 선임"",""위성시스템"",""생체흡수성 금속 리조멧""],""positive_reasons"":[""우주발사체와 위성시스템 등 신사업 진출로 성장 동력 확보"",""제이스페이스홀딩스 대표 선임을 통한 전문성 강화"",""임플란트 및 생체흡수성 금속 사업 확대가 추가 성장 기대요인""],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
3,"# 모델 역할/출력 규칙을 고정하는 시스템 프롬프트\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n - stock_related를 False로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n - stock_related를 True로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n",SK바사 해외 사업 조직 개편… 글로벌 탑티어 기업으로 성장 박차\nSK바이오사이언스가 글로벌 사업의 고도화를 위해 조직 개편을 단행했다. SK바이오사이언스는 기존 해외사업개발실을 BD Business Development 1 3실로 확대 재편하고 글로벌 규제 및 허가 전담 조직인 Global RA Regulatory Affairs 실을 신설한다고 1일 밝혔다. SK바이오사이언스는 지난해 코로나19 COVID 19 백신 위탁 생산 등으로 주목받는 백신 기업으로 부상하며 글로벌 사업의 영역과 규모가 급속도로 성장 중이다. 이러한 성장 속도에 맞춰 기존 전담 조직인 해외사업개발실을 보다 세분화 및 전문화하고자 BD 1 3실로 확대 재편했다. BD 1 3실은 앞으로 기존에 영위 중인 백신 사업뿐만 아니라 세포·유전자치료제 CGT 등 신규 사업에 대한 △글로벌 네트워크들과의 공동 개발 △신규 C D MO 수주 △개발 제품 상업화 등 다양한 영역의 사업을 고도화하고 실행력을 높이는 업무를 담당한다. 또한 Global RA실을 신설해 미국 유럽 등 해외 선진국의 GMP Good Manufacturing Practice 를 확보하는 등 국제적인 수준의 관련 인증 및 허가 획득에도 더욱 박차를 가할 방침이다. CMC팀도 신설됐다. CMC는 화학 Chemistry 제조 Manufacturing 품질 Control 의 약자다. CMC팀은 완제 의약품을 만드는 공정 개발 process development 과 품질 관리 quality control 부문에서 핵심적인 역할을 수행한다. 연구부터 임상 허가 생산 품질에 이르는 GMP 관련 제반 업무를 관리한다. SK바이오사이언스는 이번 조직 개편이 글로벌 탑티어 바이오 기업으로의 성장을 더욱 앞당기고 초격차 경쟁력 확보의 계기가 될 것으로 기대하고 있다. SK바이오사이언스는 지난달 29일 국내 최초 코로나19 백신인 스카이코비원 SKYCovione 멀티주 의 품목허가를 획득했다. 이어 국가출하승인 및 WHO 등 해외 승인을 통해 국내외 백신 시장에 본격 진출할 예정이다.,"{""stock_related"":true,""summary"":""SK바이오사이언스는 글로벌 사업의 고도화를 위해 해외사업 조직을 BD 1-3실로 세분화하고, 글로벌 규제 및 허가 전담 조직인 Global RA실과 의약품 공정개발 및 품질관리 담당 CMC팀을 신설했다. 코로나19 백신 위탁생산을 통해 급성장한 동사는 이번 조직개편으로 글로벌 백신 시장 진출과 세포·유전자치료제 등 신규 사업 고도화에 박차를 가하고 있으며, 국내 최초 코로나19 백신 품목허가를 획득해 시장 경쟁력을 강화하고 있다."",""positive_stocks"":[""SK바이오사이언스""],""positive_keywords"":[""글로벌 사업 고도화"",""조직 개편"",""백신 사업 확장"",""신규 사업"",""규제 및 허가 전담 조직"",""CMC팀 신설"",""코로나19 백신 품목허가""],""positive_reasons"":[""조직 개편으로 글로벌 네트워크와 공동 개발 및 신규 수주가 강화되어 사업 실행력이 높아짐"",""Global RA실 신설로 미국, 유럽 등 선진국 GMP 인증 및 허가 획득 탄력 전망"",""CMC팀 신설로 공정 개발과 품질 관리 강화되어 제품 경쟁력 확보"",""국내 최초 코로나19 백신 품목허가로 국내외 백신 시장 진출 기반 마련 및 브랜드 신뢰도 제고"",""글로벌 탑티어 바이오 기업으로 성장 가속화 기대""],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
4,"# 모델 역할/출력 규칙을 고정하는 시스템 프롬프트\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n - stock_related를 False로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n - stock_related를 True로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n",금융당국 “증시 변동성 완화 조치”\n4일부터 석달간 증권사 신용융자담보비율 유지의무 면제 금융당국이 코스피지수가 장중 2300 아래까지 떨어지자 주식시장 변동성을 완화하는 조치를 시행하기로 했다. 금융위원회는 1일 주식시장 마감 후 김소영 부위원장 주재로 증권 유관기관과 금융시장합동점검회의를 열고 변동성 완화조치를 시행하기로 했다고 밝혔다. 이에 따라 다음 주식시장 개장일인 오는 4일부터 9월30일까지 3개월간 증권사의 신용융자담보비율 유지의무가 면제된다. 신용융자담보비율 유지의무란 증권사가 일명 ‘빚투’ 빚내서 투자 자금인 신용융자를 시행할 때 담보를 140% 이상 확보하고 내규에서 정한 담보비율을 유지할 것을 요구하는 규제다. 유지의무 면제는 증권사의 신용융자 담보주식에 대한 과도한 반대매매를 억제하기 위한 조치다. 금융당국은 코로나19 사태가 본격화한 2020년 3월에도 이 같은 조치를 6개월간 시행한 바 있다. 7일부터 10월6일까지는 상장기업의 하루 자기주식 매수 주문 수량 한도 제한도 완화된다. 신탁취득 주식도 발행주식총수의 1% 이내에서 신탁재산 총액 범위 내로 한시적으로 확대된다. 이와 함께 금융위는 금융감독원과 한국거래소 합동으로 공매도 특별점검을 실시해 공매도 현황과 시장교란 가능성 등을 살펴보기로 했다. 현재 공매도는 지난해 5월 이후 제한적으로 실시되고 있다. 금융위와 금감원은 매주 금요일 금융시장합동점검회의를 열어 증시 등 금융시장상황을 점검할 예정이다. 금융당국은 “컨틴전시플랜에 따라 필요한 시장 변동성 완화 조치를 검토·시행해 나갈 것”이라고 말했다.,"{""stock_related"":false,""summary"":""금융당국이 최근 코스피지수 하락에 대응해 4일부터 9월30일까지 석달간 증권사의 신용융자담보비율 유지의무를 면제하는 등 증시 변동성 완화 조치를 시행한다. 또한 자기주식 매수 제한 완화, 신탁취득 주식 확대, 공매도 특별점검 실시 등 여러 대책을 도입하여 시장 안정화를 도모할 계획이다. 금융당국은 앞으로도 시장 상황에 따라 추가적인 변동성 완화 조치를 검토·시행할 예정이다."",""positive_stocks"":[],""positive_keywords"":[],""positive_reasons"":[],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
5,"# 모델 역할/출력 규칙을 고정하는 시스템 프롬프트\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n - stock_related를 False로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n - stock_related를 True로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n",씨티그룹 하반기 20% 넘게 오를 종목은 이것\n미국 뉴욕증시가 52년 만에 최악의 상반기를 보낸 가운데 씨티그룹이 랠리가 기대되는 종목들을 추천했다. 30일 현지시간 CNBC에 따르면 씨티은행은 팩트셋 자료를 인용해 올해 안으로 20% 이상의 주가 상승세를 보일 기업들을 꼽았다. 해당 기업들에 최소 10% 이상의 주당 순이익 성장세가 예상된다는 분석이다. 씨티그룹이 가장 먼저 꼽은 기업은 마이크로소프트다. 마이크로소프트는 올 들어 현재까지 주가가 23% 이상 하락했다. 그러나 분석가들은 주가가 현재 수준에서 36% 반등할 것으로 보고 있다. 이날 마이크로소프트는 전 거래일 대비 1.32% 하락한 256.83달러에서 거래를 마감했다. 씨티그룹은 마이크로소프트가 IT 사업 예산을 늘렸다는 점과 마이크로소프트가 추진하는 하이브리드 업무환경을 긍정적으로 평가하고 있다며 올해 주당 순이익이 16.5% 뛸 것으로 예상한다고 덧붙였다. 이외에도 씨티그룹은 엔터테인먼트와 에너지주에 주목했다. 디즈니의 주가는 올 들어 39% 급락하면서 52주 최고가 대비 반토막 났다. 씨티그룹은 디즈니의 주가가 이날 종가 94.40달러 대비 50% 반등할 수 있다며 주당 순이익도 올해 약 74%까지 오를 수 있다고 내다봤다. 씨티그룹은 에너지주의 랠리 가능성 또한 높게 점쳤다. 에너지주는 올 상반기 S P 500 지수 내 유일하게 올해 30% 이상 상승했다. 씨티그룹은 에너지주 중에서도 셰브론의 주당 순이익이 올해 내 두 배 이상 뛸 것이라며 유망주로 꼽았다.,"{""stock_related"":true,""summary"":""씨티그룹은 미국 뉴욕증시가 부진한 가운데 하반기에 20% 이상 상승할 것으로 기대되는 주식으로 마이크로소프트, 디즈니, 셰브론을 추천했다. 마이크로소프트는 IT 사업 예산 증가와 하이브리드 업무환경 추진을 긍정적으로 평가받아 주당 순이익이 16.5% 증가할 것으로 예상된다. 디즈니는 올해 약 74%의 주당 순이익 증가와 주가 50% 반등이 기대되고, 셰브론은 올해 주당 순이익이 두 배 이상 증가할 것으로 전망된다. 에너지주는 상반기 S&P 500 내에서 30% 이상 상승하는 등 강세를 보이고 있다."",""positive_stocks"":[""마이크로소프트"",""디즈니"",""셰브론""],""positive_keywords"":[""주가 상승"",""주당 순이익 성장"",""IT 예산 증가"",""하이브리드 업무환경"",""순이익 증가"",""에너지주 랠리"",""S&P 500 상승""],""positive_reasons"":[""마이크로소프트는 IT 사업 예산 증가와 하이브리드 업무환경 추진으로 순이익 16.5% 증가 예상"",""디즈니는 주가가 39% 급락한 후 50% 반등과 순이익 74% 증가 가능성"",""셰브론은 에너지주 강세 속에서 주당 순이익이 두 배 이상 증가할 전망"",""에너지주가 상반기 S&P 500에서 30% 이상 상승하는 등 긍정적 시장 환경""],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
6,"# 모델 역할/출력 규칙을 고정하는 시스템 프롬프트\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n - stock_related를 False로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n - stock_related를 True로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n",한국 스타트업 BMW와 에어버스에 혁신 기술 소개\n코트라 BMW 오픈이노베이션 IR 로드쇼 추진 스타트업 6개사 선발…현지서 기술 소개하고 상담 추진 기술실증 PoC 프로젝트까지 지원 이데일리 함정선 기자 한국의 스타트업들이 글로벌 기업인 BMW와 에어버스 Airbus 에 혁신 기술을 소개하고 협력 기회를 모색하는 자리가 마련됐다. KOTRA 코트라 는 한국벤처투자 BMW와 스타트업 개러지 코리아 등과 지난 6월 29일부터 7월1일까지 독일 뮌헨에서 ‘BMW 오픈이노베이션 IR 로드쇼’ 사업을 추진했다고 3일 밝혔다. 이번 BMW 오픈이노베이션 IR 로드쇼에서는 지난 4월 서울 컨벤션센터 SETEC 에서 개최된 ‘BMW 오픈이노베이션 피칭데이’를 통해 선발한 스타트업 6개사 15명이 참가했다. 참가 스타트업 6개사는 4박 5일간 독일 뮌헨을 방문해 BMW와 에어버스를 비롯한 독일의 글로벌 제조사에 자신들의 혁신 기술을 소개하고 협업을 제안했다. 6월 29일에는 BMW 그룹의 연구혁신센터에서 참가 스타트업 6개사의 피칭과 전시가 이뤄졌다. 피칭 행사에는 BMW 임직원 총 150명이 한국 스타트업의 피칭을 보기 위해 온·오프라인으로 모였고 하루 동안 총 350명이 전시 부스에 방문하는 등 BMW의 임직원들은 한국의 혁신 기술 스타트업과 협업하는 데에 큰 관심을 보였다. 이는 현장에서 일대일 상담으로 이어졌으며 코트라에 따르면 현재 참가 스타트업과 BMW그룹의 사업 부서 간 기술실증 PoC 프로젝트 추진 가능성이 논의되고 있다. 드라가나 코스틱 Dragana Kostic BMW 테크놀로지 오피스 Technology Office 아시아태평양본부 총괄은 “코로나 이후 한국의 스타트업이 본사를 직접 방문해 기술을 소개하는 것은 이번 행사가 처음”이라며 “참가한 스타트업들이 모두 우수해 앞으로 많은 협업 프로젝트가 이뤄질 것으로 기대한다”고 말했다. 6월 30일에는 뮌헨 외곽지역에 소재한 에어버스 그룹의 연구 혁신센터를 방문해 참가 스타트업 6개사의 피칭 행사를 진행했다. 에어버스 블루스카이 Blue Sky 오픈이노베이션 전담 조직 를 비롯한 그룹 내 핵심 인력을 대상으로 이루어진 이번 행사에서는 피칭 이후 질의응답까지 진행해 현장에서 기술 검증을 위한 여러 가지 논의가 이어졌다. 장 도미닉 코스트 Jean Dominique Coste 에어버스 블루스카이 그룹장은 “에어버스는 한국 스타트업과의 기술협력을 위해 모든 가능성을 열어두고 지속적으로 논의할 것”이라고 말했다. 이외에도 참가 스타트업 중 2개사는 이번 출장 기간 중 100년의 역사를 자랑하는 글로벌 자동차 부품기업인 베바스토 Webasto 자율주행·정밀엔지니어링 기업인 아큐론 Accuron 도 방문해 일대일 상담을 진행하고 협업 가능성을 논의했다. 참가 스타트업 6개사는 △AI 가상인간 D사 △인공신경망처리장치 NPU 기반 AI 반도체 D사 △친환경 가죽 시트 및 가죽실 제조사 A사 △클라우드 기반 VR 및 메타버스 솔루션 I사 △개발자용 AI 비서 L사 △디지털 ID 인증 및 보안솔루션 S사 등이며 한국에 돌아온 이후 BMW 및 에어버스와의 협업 프로젝트를 본격적으로 추진할 예정이다. 유정열 코트라 사장은 “글로벌기업과의 협업은 우리 스타트업이 해외 시장에서 스케일업할 수 있는 매우 중요한 기회”라며 “코트라의 128개 해외무역관이 우리 스타트업의 손과 발이 돼 현지의 글로벌기업과 협업할 기회를 지속적으로 만들어 나갈 것”이라고 밝혔다. BMW FIZ Center 연구혁신센터 에서 참가 스타트업이 BMW 직원을 대상으로 피칭을 진행하고 있다.,"{""stock_related"":true,""summary"":""한국 스타트업 6개사가 독일 뮌헨에서 BMW와 에어버스 등 글로벌 제조사에 혁신 기술을 소개하고 협업 기회를 모색하는 BMW 오픈이노베이션 IR 로드쇼가 개최되었다. 피칭 및 전시를 통해 현장 일대일 상담과 기술실증 PoC 프로젝트 추진 가능성이 논의되고 있으며, 에어버스와 베바스토, 아큐론 등과의 협력도 적극 추진 중이다. 코트라는 이를 스타트업 해외 시장 진출과 스케일업의 중요한 기회로 보고 있다."",""positive_stocks"":[""BMW"",""에어버스"",""베바스토"",""아큐론""],""positive_keywords"":[""협력 기회"",""혁신 기술 소개"",""PoC 프로젝트"",""기술 실증"",""스타트업 스케일업"",""글로벌 협업""],""positive_reasons"":[""BMW와 에어버스 등 글로벌 대기업과의 협업으로 기술개발 및 사업 확장 가능성이 높음"",""PoC 프로젝트 추진 가능성은 실질적인 사업화 단계 진입을 의미"",""코트라의 지원으로 해외 시장 진출 및 글로벌 네트워크 강화 기대"",""스타트업들의 혁신 기술이 글로벌 제조사들의 관심을 받아 향후 매출 및 기술력 향상에 긍정적 영향""],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
7,"# 모델 역할/출력 규칙을 고정하는 시스템 프롬프트\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n - stock_related를 False로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n - stock_related를 True로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n",과기부 허준이 필즈상 기쁜 소식…한국 수학 발전 기대\n정부가 허준이 미국 프린스턴대 교수 겸 한국 고등과학원 수학부 석학교수의 필즈상 수상을 축하했습니다. 과학기술정보통신부는 대수기하학의 토대가 더욱 확장되도록 새 지평을 연 공로를 인정받아 한국계 최초로 필즈상 수상의 쾌거를 이룩했다 며 축하했습니다. 또 허 교수의 필즈상 수상은 올해 국제수학연맹에서 한국의 수학 국가등급을 최고등급으로 상향한 것에 이은 기쁜 소식 이라며 허 교수의 행보와 한국 수학계의 지속적 발전 역시 기대된다고 덧붙였습니다.,"{""stock_related"":false,""summary"":""과학기술정보통신부는 허준이 교수가 미국 프린스턴대학교 교수 겸 한국 고등과학원 석학교수로서 대수기하학 분야에서의 공로로 한국계 최초로 필즈상 수상을 축하했습니다. 이번 수상은 한국 수학의 국가 등급이 최고 등급으로 상향된 것에 이은 긍정적 소식으로, 앞으로 한국 수학계의 지속적인 발전이 기대됩니다."",""positive_stocks"":[],""positive_keywords"":[],""positive_reasons"":[],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
8,"# 모델 역할/출력 규칙을 고정하는 시스템 프롬프트\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n - stock_related를 False로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n - stock_related를 True로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n",가뭄 영향에... 금배추 됐네\n서울 뉴시스 고승민 기자 한국농촌경제연구원 농업관측센터 농업관측 엽근채소 7호 보고서에 따르면 이달 배추 도매가격이 10kg 기준 1만500원을 기록할 것으로 예상된 3일 서울의 한 대형마트에 배추가 진열돼 있다. 이는 작년과 비교하면 90.9% 평년보다 39% 상승한 수치다. 연구원은 가뭄 등 날씨 영향으로 작황이 부진하고 재배면적도 감소하면서 배추 생산량이 줄었기 때문으로 보고 있다. 2022.07.03. kkssmm99 newsis.com 사진 영상 제보받습니다 공감언론 뉴시스가 독자 여러분의 소중한 제보를 기다립니다. 뉴스 가치나 화제성이 있다고 판단되는 사진 또는 영상을 뉴시스 사진영상부 n photo newsis.com 로 보내주시면 적극 반영하겠습니다.,"{""stock_related"":false,""summary"":""한국농촌경제연구원 농업관측센터 보고서에 따르면 가뭄과 날씨 영향으로 배추 작황이 부진하고 재배면적도 감소하여 배추 생산량이 크게 줄면서 7월 초 배추 도매가격이 지난해 대비 90.9%, 평년 대비 39% 상승할 것으로 예상된다. 이는 소비자 물가에 영향을 미칠 수 있는 농산물 가격 상승에 대한 우려를 나타낸다."",""positive_stocks"":[],""positive_keywords"":[],""positive_reasons"":[],""negative_stocks"":[],""negative_keywords"":[],""negative_reasons"":[]}"
9,"# 모델 역할/출력 규칙을 고정하는 시스템 프롬프트\n당신은 금융/경제 뉴스의 핵심내용을 요약해 설명하고,\n특정 상장 종목에 미치는 긍정/부정 영향여부, 이유, 근거를 분석하는 금융/경제 분석 전문가입니다.\n\n다음 출력지시사항을 지켜주세요.\n1. 뉴스와 종목간의 연관성을 발견할 수 없다면:\n - stock_related를 False로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n2. 뉴스와 종목간의 연관성을 발견했다면:\n - stock_related를 True로 작성하세요.\n - summary에 뉴스의 요약을 작성하세요.\n - 긍정영향이 예상되는 종목이 있다면, positive_stocks, positive_keywords, positive_reasons를 작성하세요.\n - 부정영향이 예상되는 종목이 있다면, negative_stocks, negative_keywords, negative_reasons를 작성하세요.\n - 값이 없는 경우 빈 문자열(''), 빈 리스트([])로 작성하세요.\n",특징주 삼성전자·SK하이닉스 또다시 52주 신저가 추락\n삼성전자 SK하이닉스 CG 연합뉴스TV 제공 서울 연합뉴스 김아람 기자 삼성전자와 SK하이닉스가 4일 오전 재차 52주 신저가를 경신했다. 이날 오전 9시 5분 현재 유가증권시장에서 삼성전자는 전 거래일보다 0.53% 내린 5만5천900원에 거래 중이다. SK하이닉스도 전날보다 1.14% 내린 8만6천500원에 거래됐다. 개장 직후 삼성전자는 5만5천700원 SK하이닉스는 8만6천300원까지 낙폭을 키워 이틀 연속 52주 신저가를 새로 썼다. 최근 반도체 업황 우려가 확산하면서 두 종목 주가는 하락세를 이어왔다.,"{""stock_related"":true,""summary"":""삼성전자와 SK하이닉스가 이틀 연속 52주 신저가를 경신하며 주가가 하락했다. 반도체 업황에 대한 우려가 확산되면서 두 종목의 주가가 약세를 보이고 있다."",""positive_stocks"":[],""positive_keywords"":[],""positive_reasons"":[],""negative_stocks"":[""삼성전자"",""SK하이닉스""],""negative_keywords"":[""반도체 업황 우려"",""52주 신저가"",""주가 하락""],""negative_reasons"":[""반도체 업황에 대한 시장 불안 확산으로 인해 투자 심리가 위축되면서 두 회사의 주가가 지속 하락세를 보임. 이로 인해 단기적으로 두 종목에 부정적인 영향이 예상됨.""]}"

In [18]:
# DataFrame을 JSON 파일로 저장
df[['system', 'user', 'assistant']].to_json(
    'train_json',           #  저장 파일명(경로)
    orient = 'records',     #  리스트 형태로 저장
    force_ascii=False,      #  한글 깨짐 방지
    indent=4                #  들여쓰기 4칸
)

import os 
from datasets import Dataset

dataset = Dataset.from_pandas(df[['system', 'user', 'assistant']])
dataset.push_to_hub(
    'clachic/naver-economy-news2stock'    
)

Creating parquet from Arrow format: 100%|██████████| 1/1 [00:00<00:00, 118.96ba/s]
Processing Files (1 / 1): 100%|██████████| 93.7kB / 93.7kB, 46.9kB/s
New Data Upload: 100%|██████████| 93.7kB / 93.7kB, 46.9kB/s
Uploading the dataset shards: 100%|██████████| 1/1 [00:03<00:00,  3.09s/ shards]

CommitInfo(commit_url='https://huggingface.co/datasets/clachic/naver-economy-news2stock/commit/4cf134e3ef3d647c6a942163b69135adc91a911b', commit_message='Upload dataset', commit_description='', oid='4cf134e3ef3d647c6a942163b69135adc91a911b', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/clachic/naver-economy-news2stock', endpoint='https://huggingface.co', repo_type='dataset', repo_id='clachic/naver-economy-news2stock'), pr_revision=None, pr_num=None)

In [19]:
from datasets import load_dataset

ds = load_dataset("capybaraOh/naver-economy-news2stock")

c:\Users\Playdata\llm\llm_venv\Lib\site-packages\huggingface_hub\file_download.py:130: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Playdata\.cache\huggingface\hub\datasets--capybaraOh--naver-economy-news2stock. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)
Generating train split: 100%|██████████| 1000/1000 [00:00<00:00, 14907.89 examples/s]

In [21]:
ds.push_to_hub(
    'clachic/naver-economy-news2stock'
)

Creating parquet from Arrow format: 100%|██████████| 1/1 [00:00<00:00, 43.32ba/s]
Processing Files (1 / 1): 100%|██████████| 1.91MB / 1.91MB, 1.06MB/s
New Data Upload: |          |  0.00B /  0.00B,  0.00B/s
Uploading the dataset shards: 100%|██████████| 1/1 [00:02<00:00,  2.62s/ shards]
c:\Users\Playdata\llm\llm_venv\Lib\site-packages\huggingface_hub\file_download.py:130: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\Playdata\.cache\huggingface\hub\datasets--clachic--naver-economy-news2stock. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

CommitInfo(commit_url='https://huggingface.co/datasets/clachic/naver-economy-news2stock/commit/2e44a6023124cdfe45b4ab12bef795287c0d0ba9', commit_message='Upload dataset', commit_description='', oid='2e44a6023124cdfe45b4ab12bef795287c0d0ba9', pr_url=None, repo_url=RepoUrl('https://huggingface.co/datasets/clachic/naver-economy-news2stock', endpoint='https://huggingface.co', repo_type='dataset', repo_id='clachic/naver-economy-news2stock'), pr_revision=None, pr_num=None)